<?php
/* contiene un conjunto de posibles causas de problemas en un vehiculo, cada una con palabras clave asociadas y 
 recomendaciones para su solucion. la clase tiene un metodo diagnosticar que toma un texto de entrada, lo normaliza y 
 busca coincidencias con las palabras clave de cada causa para determinar posibles problemas y su nivel de confianza, 
 los resultados se ordenan por confianza y se devuelven los tres mas relevantes */

class MotorDiagnosticoIA
{
    private array $causas = [
        [
            'clave' => 'bateria',
            'titulo' => 'bateria descargada o en mal estado',
            'keywords' => [
                'bateria',
                'bateria descargada',
                'bateria baja',
                'bateria muerta',
                'sin bateria',
                'no arranca',
                'le cuesta arrancar',
                'tarda en arrancar',
                'tarda mucho en arrancar',
                'arranque lento',
                'motor gira lento',
                'gira lento',
                'luces flojas',
                'luces debiles',
                'luces bajas',
                'luces del cuadro flojas',
                'cuadro flojo',
                'cuadro se apaga',
                'click al arrancar',
                'hace click',
                'por las mananas',
                'en frio no arranca',
                'no tiene fuerza para arrancar',
                'bateria descarregada',
                'bateria baixa',
                'bateria morta',
                'sense bateria',
                'no arrenca',
                'li costa arrencar',
                'triga a arrencar',
                'triga molt a arrencar',
                'arrencada lenta',
                'motor gira lent',
                'gira lent',
                'llums fluixos',
                'llums febles',
                'llums baixes',
                'llums del quadre fluixes',
                'quadre fluix',
                'quadre s apaga',
                'clic en arrencar',
                'fa clic',
                'al mati',
                'pels matins',
                'en fred no arrenca',
                'no te força per arrencar'
            ],
            'recomendacion' => 'revisar la carga de la bateria, bornes y alternador antes de sustituirla.'
        ],
        [
            'clave' => 'arranque',
            'titulo' => 'fallo en el motor de arranque',
            'keywords' => [
                'motor de arranque',
                'fallo de arranque',
                'no gira',
                'motor no gira',
                'no hace nada',
                'llave y no hace nada',
                'giro la llave',
                'al girar la llave',
                'silencio al arrancar',
                'no se escucha nada',
                'solo hace click',
                'click seco',
                'arranque no responde',
                'no mueve el motor',
                'no intenta arrancar',
                'no acciona el arranque',
                'motor d arrencada',
                'fallada d arrencada',
                'no gira',
                'motor no gira',
                'no fa res',
                'clau i no fa res',
                'giro la clau',
                'en girar la clau',
                'silenci en arrencar',
                'no se sent res',
                'nomes fa clic',
                'clic sec',
                'arrencada no respon',
                'no mou el motor',
                'no intenta arrencar',
                'no acciona l arrencada'
            ],
            'recomendacion' => 'comprobar motor de arranque, relé y conexiones electricas.'
        ],
        [
            'clave' => 'encendido',
            'titulo' => 'problema de bujias o encendido',
            'keywords' => [
                'bujias',
                'bobinas',
                'encendido',
                'fallo de encendido',
                'tirones',
                'da tirones',
                'tironea',
                'ratea',
                'rateo',
                'motor vibra',
                'vibra el motor',
                'vibraciones del motor',
                'ralenti inestable',
                'ralenti irregular',
                'falla al acelerar',
                'fallos al acelerar',
                'pierde potencia',
                'perdida de potencia',
                'perdida potencia',
                'explosiones',
                'petardea',
                'consume mucha gasolina',
                'huele a gasolina',
                'funciona a tirones',
                'bugies',
                'bobines',
                'encesa',
                'fallada d encesa',
                'estrebades',
                'fa estrebades',
                'dona estrebades',
                'rateja',
                'rateig',
                'motor vibra',
                'vibra el motor',
                'vibracions del motor',
                'ralenti inestable',
                'ralenti irregular',
                'falla en accelerar',
                'fallades en accelerar',
                'perd potencia',
                'perdua de potencia',
                'perdua potencia',
                'explosions',
                'petardeja',
                'consumeix molta gasolina',
                'fa olor de gasolina',
                'funciona a estrebades'
            ],
            'recomendacion' => 'revisar bujias, bobinas y sistema de encendido.'
        ],
        [
            'clave' => 'filtros',
            'titulo' => 'filtro de aire o combustible obstruido',
            'keywords' => [
                'filtro',
                'filtro de aire',
                'filtro de combustible',
                'filtro sucio',
                'obstruido',
                'ahogado',
                'coche ahogado',
                'acelera poco',
                'le cuesta acelerar',
                'poca fuerza',
                'no tiene fuerza',
                'pierde fuerza',
                'pierde potencia',
                'perdida de potencia',
                'perdida potencia',
                'en carretera',
                'subiendo cuestas',
                'consume mucho',
                'consumo alto',
                'no responde al acelerar',
                'se queda sin fuerza',
                'le falta aire',
                'filtre',
                'filtre d aire',
                'filtre de combustible',
                'filtre brut',
                'obstruit',
                'ofegat',
                'cotxe ofegat',
                'accelera poc',
                'li costa accelerar',
                'poca força',
                'no te força',
                'perd força',
                'perd potencia',
                'perdua de potencia',
                'perdua potencia',
                'a carretera',
                'pujant costes',
                'consumeix molt',
                'consum alt',
                'no respon en accelerar',
                'es queda sense força',
                'li falta aire'
            ],
            'recomendacion' => 'revisar filtros y sustituirlos si estan sucios.'
        ],
        [
            'clave' => 'sobrecalentamiento',
            'titulo' => 'sobrecalentamiento del motor',
            'keywords' => [
                'temperatura alta',
                'temperatura muy alta',
                'sube la temperatura',
                'temperatura sube',
                'aguja temperatura',
                'aguja sube',
                'se calienta',
                'se calienta mucho',
                'motor caliente',
                'motor muy caliente',
                'sobrecalentamiento',
                'calienta en ciudad',
                'se calienta parado',
                'sale humo',
                'humo del motor',
                'humo capo',
                'anticongelante',
                'refrigerante',
                'pierde anticongelante',
                'pierde refrigerante',
                'pierde liquido refrigerante',
                'radiador',
                'termostato',
                'ventilador',
                'ventilador no funciona',
                'ventilador no salta',
                'hierve el agua',
                'vaso expansion',
                'nivel refrigerante bajo',
                'temperatura alta',
                'temperatura molt alta',
                'puja la temperatura',
                'temperatura puja',
                'agulla temperatura',
                'agulla puja',
                's escalfa',
                's escalfa molt',
                'motor calent',
                'motor molt calent',
                'sobreescalfament',
                's escalfa a ciutat',
                's escalfa parat',
                'surt fum',
                'fum del motor',
                'fum capo',
                'anticongelant',
                'refrigerant',
                'perd anticongelant',
                'perd refrigerant',
                'perd liquid refrigerant',
                'radiador',
                'termostat',
                'ventilador',
                'ventilador no funciona',
                'ventilador no salta',
                'bull l aigua',
                'vas expansio',
                'nivell refrigerant baix'
            ],
            'recomendacion' => 'parar el vehiculo y revisar refrigerante, radiador, termostato y ventilador.'
        ],
        [
            'clave' => 'frenos',
            'titulo' => 'fallo en frenos',
            'keywords' => [
                'frenos',
                'freno',
                'frena poco',
                'no frena bien',
                'le cuesta frenar',
                'pedal blando',
                'pedal de freno blando',
                'freno blando',
                'freno esta blando',
                'pedal se hunde',
                'ruido frenos',
                'ruido al frenar',
                'hace ruido al frenar',
                'chirrido',
                'chirrido al frenar',
                'pastillas',
                'discos',
                'liquido de frenos',
                'vibra al frenar',
                'vibra cuando freno',
                'freno fuerte',
                'cuando freno',
                'frenada larga',
                'olor a quemado al frenar',
                'frens',
                'fre',
                'frena poc',
                'no frena be',
                'li costa frenar',
                'pedal tou',
                'pedal de fre tou',
                'fre tou',
                'fre esta tou',
                'pedal s enfonsa',
                'soroll frens',
                'soroll en frenar',
                'fa soroll en frenar',
                'grinyol',
                'grinyol en frenar',
                'pastilles',
                'discos',
                'liquid de frens',
                'vibra en frenar',
                'vibra quan freno',
                'fre fort',
                'quan freno',
                'frenada llarga',
                'olor de cremat en frenar'
            ],
            'recomendacion' => 'revisar pastillas, discos, liquido de frenos y posibles fugas.'
        ],
        [
            'clave' => 'embrague',
            'titulo' => 'problema de embrague',
            'keywords' => [
                'embrague',
                'patina',
                'embrague patina',
                'no entran marchas',
                'marchas entran mal',
                'las marchas entran mal',
                'cuesta meter marchas',
                'cuesta cambiar',
                'cambio duro',
                'rascan las marchas',
                'rasca al cambiar',
                'pedal duro',
                'pedal esta duro',
                'pedal de embrague duro',
                'olor quemado',
                'huele a quemado',
                'olor a embrague',
                'embrague quemado',
                'suben revoluciones y no anda',
                'revoluciones suben pero no acelera',
                'embragatge',
                'patina',
                'embragatge patina',
                'no entren marxes',
                'marxes entren malament',
                'les marxes entren malament',
                'costa posar marxes',
                'costa canviar',
                'canvi dur',
                'rasquen les marxes',
                'rasca en canviar',
                'pedal dur',
                'pedal esta dur',
                'pedal d embragatge dur',
                'olor de cremat',
                'fa olor de cremat',
                'olor d embragatge',
                'embragatge cremat',
                'pugen revolucions i no camina',
                'revolucions pugen pero no accelera'
            ],
            'recomendacion' => 'revisar desgaste del embrague y sistema hidraulico.'
        ],
        [
            'clave' => 'neumaticos',
            'titulo' => 'neumaticos o alineacion incorrecta',
            'keywords' => [
                'neumaticos',
                'ruedas',
                'alineacion',
                'direccion',
                'volante',
                'vibra el volante',
                'volante vibra',
                'vibracion volante',
                'se va a un lado',
                'se va hacia un lado',
                'coche se va hacia un lado',
                'tira a la derecha',
                'tira a la izquierda',
                'desgaste irregular',
                'desgaste raro',
                'ruedas se desgastan raro',
                'desgasta una rueda',
                'presion ruedas',
                'presion baja',
                'equilibrado',
                'vibra en carretera',
                'vibra a velocidad',
                'direccion torcida',
                'pneumatics',
                'rodes',
                'alineacio',
                'direccio',
                'volant',
                'vibra el volant',
                'volant vibra',
                'vibracio volant',
                'se n va cap a un costat',
                'se n va a un costat',
                'cotxe se n va cap a un costat',
                'tira a la dreta',
                'tira a l esquerra',
                'desgast irregular',
                'desgast estrany',
                'rodes es desgasten estrany',
                'desgasta una roda',
                'pressio rodes',
                'pressio baixa',
                'equilibrat',
                'vibra a carretera',
                'vibra a velocitat',
                'direccio torta'
            ],
            'recomendacion' => 'comprobar presion, equilibrado, alineacion y estado de los neumaticos.'
        ],
    ];

    // diagnosticar posibles causas basandose en las palabras clave encontradas en el texto del usuario
    public function diagnosticar(string $texto): array
    {
        $texto_normalizado = $this->normalizar($texto);
        $resultados = [];

        foreach ($this->causas as $causa) {
            $coincidencias = 0;

            foreach ($causa['keywords'] as $keyword) {
                if (str_contains($texto_normalizado, $this->normalizar($keyword))) {
                    $coincidencias++;
                }
            }

            if ($coincidencias > 0) {
                $confianza = min(100, (int) round(($coincidencias / 4) * 100));

                $resultados[] = [
                    'titulo' => t('diagnostico.causa.' . $causa['clave'] . '.titulo'),
                    'coincidencias' => $coincidencias,
                    'confianza' => $confianza,
                    'recomendacion' => t('diagnostico.causa.' . $causa['clave'] . '.recomendacion'),
                ];
            }
        }

        usort($resultados, function ($a, $b) {
            return $b['confianza'] <=> $a['confianza'];
        });

        return array_slice($resultados, 0, 3);
    }

    // normaliza el texto convirtiendolo a minusculas, eliminando acentos y espacios innecesarios para facilitar la comparacion con las palabras clave    
    private function normalizar(string $texto): string
    {
        $texto = mb_strtolower($texto, 'UTF-8');
        $texto = trim($texto);

        $acentos = ['á', 'é', 'í', 'ó', 'ú', 'ñ'];
        $sin_acentos = ['a', 'e', 'i', 'o', 'u', 'n'];

        return str_replace($acentos, $sin_acentos, $texto);
    }
}
