<?php

return [
    // navabar
    'navbar.inicio' => 'Inici',
    'navbar.login' => 'Iniciar sessió',
    'navbar.registro' => 'Registrar-se',
    'navbar.garaje' => 'El meu garatge',
    'navbar.comunidad' => 'Comunitat',
    'navbar.diagnostico' => 'Diagnòstic',
    'navbar.perfil' => 'El meu perfil',
    'navbar.admin' => 'Panell d’administració',
    'navbar.logout' => 'Tancar sessió',

    'navbar.idioma_es' => 'ES',
    'navbar.idioma_ca' => 'CA',
    'navbar.cambiar_idioma' => 'Canviar idioma',

    // auth - login
    'auth.login.titulo_pagina' => 'Iniciar sessió',
    'auth.login.titulo' => 'Iniciar sessió',
    'auth.login.email' => 'Correu electrònic',
    'auth.login.password' => 'Contrasenya',
    'auth.login.boton' => 'Entrar',
    'auth.login.password_olvidada' => 'He oblidat la contrasenya',

    // auth - registro
    'auth.registro.titulo_pagina' => 'Registrar-se',
    'auth.registro.titulo' => 'Registrar-se',
    'auth.registro.nombre' => 'Nom d’usuari',
    'auth.registro.nombre_ayuda' => 'Només lletres minúscules, números, punts i guions baixos, sense espais, sense punts consecutius i sense acabar en punt',
    'auth.registro.email' => 'Correu electrònic',
    'auth.registro.password' => 'Contrasenya',
    'auth.registro.password_repetida' => 'Repetir contrasenya',
    'auth.registro.password_ayuda' => 'Mínim 8 caràcters, una majúscula, una minúscula i un número',
    'auth.registro.error_password_repetida' => 'Les contrasenyes no coincideixen',
    'auth.registro.boton' => 'Crear compte',

    // auth - recuperación
    'auth.password_olvidada.titulo_pagina' => 'Recuperar contrasenya',
    'auth.password_olvidada.titulo' => 'Recuperar contrasenya',
    'auth.password_olvidada.email' => 'Correu electrònic',
    'auth.password_olvidada.boton' => 'Enviar enllaç de recuperació',
    'auth.password_olvidada.volver_login' => 'Tornar a iniciar sessió',

    // auth - restablecer contraseña
    'auth.password_restablecer.titulo_pagina' => 'Restablir contrasenya',
    'auth.password_restablecer.titulo' => 'Restablir contrasenya',
    'auth.password_restablecer.password' => 'Nova contrasenya',
    'auth.password_restablecer.password_repetida' => 'Repetir contrasenya',
    'auth.password_restablecer.boton' => 'Guardar nova contrasenya',

    // auth - mensajes
    'auth.error.rellena_login' => 'Omple el correu electrònic i la contrasenya',
    'auth.error.servidor' => 'Error de servidor, intenta-ho més tard',
    'auth.error.credenciales' => 'Credencials incorrectes',
    'auth.ok.sesion_iniciada' => 'Sessió iniciada',
    'auth.ok.sesion_cerrada' => 'Sessió tancada correctament',

    'auth.error.registro_obligatorios' => 'Has d’omplir el nom d’usuari, el correu electrònic i la contrasenya',
    'auth.error.password_no_coincide' => 'Les contrasenyes no coincideixen',
    'auth.error.nombre_requisitos' => 'El nom d’usuari només pot contenir lletres minúscules, números, punts i guions baixos, sense espais, sense punts consecutius i sense acabar en punt',
    'auth.error.password_requisitos' => 'La contrasenya ha de tenir mínim 8 caràcters, una majúscula, una minúscula i un número',
    'auth.error.nombre_uso' => 'Aquest nom d’usuari ja està en ús',
    'auth.error.email_registrado' => 'Aquest correu electrònic ja està registrat',
    'auth.ok.registro_completado' => 'Registre completat, ara inicia sessió',
    'auth.error.nombre_email_uso' => 'El nom d’usuari o el correu electrònic ja estan en ús',
    'auth.error.registro_error' => 'S’ha produït un error en registrar el compte',

    'auth.error.email_no_valido' => 'El correu electrònic no és vàlid',
    'auth.ok.recuperacion_enviada' => 'Si el correu existeix, rebràs un enllaç per restablir la contrasenya',
    'auth.error.token_no_valido' => 'Token no vàlid',
    'auth.error.enlace_expirado' => 'L’enllaç ja no és vàlid o ha caducat',
    'auth.error.enlace_restablecer_no_valido' => 'L’enllaç per restablir la contrasenya no és vàlid',
    'auth.error.campos_obligatorios' => 'Tots els camps són obligatoris',
    'auth.error.password_minimos' => 'La contrasenya no compleix els requisits mínims',
    'auth.ok.password_restablecida' => 'Contrasenya restablerta correctament',

    // inici
    'inicio.titulo_pagina' => 'Inici',
    'inicio.titulo' => 'Inici',
    'inicio.saludo' => 'Hola',
    'inicio.bienvenida' => 'Benvingut a TorqHub',

    // garatge - llistat
    'garaje.index.titulo_pagina' => 'El meu garatge',
    'garaje.index.titulo' => 'El meu garatge',
    'garaje.index.anadir_vehiculo' => 'Afegir vehicle',
    'garaje.index.sin_vehiculos' => 'Encara no tens vehicles',
    'garaje.index.ver' => 'Veure',
    'garaje.index.editar' => 'Editar',
    'garaje.index.eliminar' => 'Eliminar',

    // garatge - formulari vehicle
    'garaje.form.nuevo.titulo_pagina' => 'Afegir vehicle',
    'garaje.form.nuevo.titulo' => 'Afegir vehicle',
    'garaje.form.editar.titulo_pagina' => 'Editar vehicle',
    'garaje.form.editar.titulo' => 'Editar vehicle',

    'garaje.form.error.cargar_editar' => 'No s’ha pogut carregar el vehicle per editar',

    'garaje.form.marca' => 'Marca',
    'garaje.form.modelo' => 'Model',
    'garaje.form.any' => 'Any',
    'garaje.form.vin_opcional' => 'VIN',
    'garaje.form.vin' => 'VIN',
    'garaje.form.consultar_vin' => 'Consultar VIN',
    'garaje.form.vin_ayuda_nuevo' => 'Introdueix un VIN real de 17 caràcters per autocompletar dades del vehicle',
    'garaje.form.vin_ayuda_editar' => 'Si consultes el VIN, s’intentaran autocompletar les dades disponibles',

    'garaje.form.carroceria' => 'Carrosseria',
    'garaje.form.tipo_combustible' => 'Tipus de combustible',
    'garaje.form.tipo_cambio' => 'Tipus de canvi',
    'garaje.form.selecciona_opcion' => 'Selecciona una opció',

    'garaje.form.potencia_cv' => 'Potència (CV)',
    'garaje.form.cilindrada_cm3' => 'Cilindrada (cm³)',

    'garaje.form.imagen' => 'Imatge del vehicle',
    'garaje.form.imagen_ayuda_nuevo' => 'Formats permesos: JPG, PNG o WEBP. Màxim 3 MB',
    'garaje.form.cambiar_imagen' => 'Canviar imatge del vehicle',
    'garaje.form.cambiar_imagen_ayuda' => 'Si puges una imatge nova, substituirà l’actual. Màxim 3 MB',
    'garaje.form.imagen_actual' => 'Imatge actual',
    'garaje.form.alt_imagen_actual' => 'Imatge actual del vehicle',

    'garaje.form.cancelar' => 'Cancel·lar',
    'garaje.form.guardar_vehiculo' => 'Guardar vehicle',
    'garaje.form.guardar_cambios' => 'Guardar canvis',

    // garatge - missatges javascript
    'garaje.js.campo.marca' => 'la marca',
    'garaje.js.campo.modelo' => 'el model',
    'garaje.js.campo.any' => 'l’any',
    'garaje.js.campo.vin' => 'el VIN',
    'garaje.js.campo.carroceria' => 'la carrosseria',
    'garaje.js.campo.tipo_combustible' => 'el tipus de combustible',
    'garaje.js.campo.tipo_cambio' => 'el tipus de canvi',
    'garaje.js.campo.potencia_cv' => 'la potència',
    'garaje.js.campo.cilindrada_cm3' => 'la cilindrada',
    'garaje.js.campo.imagen' => 'la imatge',
    'garaje.js.campo.este_campo' => 'aquest camp',

    'garaje.js.error.falta' => 'Falta {campo}',
    'garaje.js.error.any_rango' => 'L’any ha d’estar entre {minimo} i {maximo}',
    'garaje.js.error.potencia_entero' => 'La potència ha de ser un número enter positiu',
    'garaje.js.error.cilindrada_entero' => 'La cilindrada ha de ser un número enter positiu',
    'garaje.js.error.imagen_tipo' => 'Només es permeten imatges JPG, PNG o WEBP',
    'garaje.js.error.imagen_tamanyo' => 'La imatge no pot superar els 3 MB',

    'garaje.js.vin.no_preparar' => 'No s’ha pogut preparar la consulta VIN',
    'garaje.js.vin.introduce' => 'Introdueix un VIN abans de consultar',
    'garaje.js.vin.formato' => 'El VIN ha de tenir 17 caràcters i no pot contenir I, O ni Q',
    'garaje.js.vin.consultando_boton' => 'Consultant...',
    'garaje.js.vin.consultando_mensaje' => 'Consultant VIN...',
    'garaje.js.vin.respuesta_no_json' => 'La resposta del servidor no és JSON vàlid',
    'garaje.js.vin.no_consultar' => 'No s’ha pogut consultar el VIN',
    'garaje.js.vin.origen_cache' => 'memòria cau local',
    'garaje.js.vin.origen_api' => 'API externa',
    'garaje.js.vin.ok_desde' => 'VIN consultat correctament des de {origen}',

    // garatge - detall vehicle
    'garaje.detalle.titulo_pagina' => 'Detall del vehicle',
    'garaje.detalle.titulo' => 'Detall del vehicle',
    'garaje.detalle.error.cargar' => 'No s’ha pogut carregar el vehicle',
    'garaje.detalle.alt_imagen' => 'Imatge del vehicle',
    'garaje.detalle.imagen_no_disponible' => 'Imatge no disponible',
    'garaje.detalle.imagen_ayuda' => 'Encara no s’ha pujat cap foto per a aquest vehicle',
    'garaje.detalle.subtitulo' => 'Vehicle registrat al teu garatge',
    'garaje.detalle.volver_garaje' => 'Tornar al garatge',
    'garaje.detalle.editar' => 'Editar',
    'garaje.detalle.eliminar' => 'Eliminar',
    'garaje.detalle.estadisticas' => 'Estadístiques ràpides',
    'garaje.detalle.total_gastado' => 'Total gastat',
    'garaje.detalle.mantenimientos' => 'Manteniments',
    'garaje.detalle.ultimo_mantenimiento' => 'Últim manteniment',
    'garaje.detalle.sin_registros' => 'Sense registres',
    'garaje.detalle.no_indicado' => 'No indicat',
    'garaje.detalle.marca' => 'Marca',
    'garaje.detalle.modelo' => 'Model',
    'garaje.detalle.any' => 'Any',
    'garaje.detalle.vin' => 'VIN',
    'garaje.detalle.carroceria' => 'Carrosseria',
    'garaje.detalle.tipo_combustible' => 'Tipus de combustible',
    'garaje.detalle.tipo_cambio' => 'Tipus de canvi',
    'garaje.detalle.potencia' => 'Potència',
    'garaje.detalle.cilindrada' => 'Cilindrada',
    'garaje.detalle.fecha_alta' => 'Data d’alta',

    // garatge - historial
    'garaje.historial.titulo' => 'Historial de manteniment',
    'garaje.historial.anadir' => 'Afegir manteniment',
    'garaje.historial.exportar_csv' => 'Exportar CSV',
    'garaje.historial.tipo' => 'Tipus',
    'garaje.historial.todos' => 'Tots',
    'garaje.historial.fecha_desde' => 'Data des de',
    'garaje.historial.fecha_hasta' => 'Data fins a',
    'garaje.historial.km_minimos' => 'Km mínims',
    'garaje.historial.km_maximos' => 'Km màxims',
    'garaje.historial.coste_minimo' => 'Cost mínim',
    'garaje.historial.coste_maximo' => 'Cost màxim',
    'garaje.historial.ordenar_por' => 'Ordenar per',
    'garaje.historial.fecha' => 'Data',
    'garaje.historial.kilometros' => 'Quilòmetres',
    'garaje.historial.coste' => 'Cost',
    'garaje.historial.direccion' => 'Direcció',
    'garaje.historial.descendente' => 'Descendent',
    'garaje.historial.ascendente' => 'Ascendent',
    'garaje.historial.filtrar' => 'Filtrar',
    'garaje.historial.limpiar' => 'Netejar',
    'garaje.historial.error_ajax' => 'No s’ha pogut actualitzar l’historial',
    'garaje.historial.total_visibles' => 'Total visibles',
    'garaje.historial.coste_total_visible' => 'Cost total visible',
    'garaje.historial.primer_resultado' => 'Primer resultat',
    'garaje.historial.sin_resultados' => 'Sense resultats',
    'garaje.historial.anterior' => 'Anterior',
    'garaje.historial.siguiente' => 'Següent',
    'garaje.historial.sin_mantenimientos' => 'No hi ha manteniments que coincideixin amb els filtres aplicats',
    'garaje.historial.descripcion' => 'Descripció',
    'garaje.historial.acciones' => 'Accions',
    'garaje.historial.no_indicada' => 'No indicada',
    'garaje.historial.no_indicados' => 'No indicats',
    'garaje.historial.editar' => 'Editar',
    'garaje.historial.eliminar' => 'Eliminar',
    'garaje.historial.confirmar_eliminar' => 'Segur que vols eliminar aquest manteniment?',

    // garatge - formulari manteniment
    'garaje.mantenimiento.nuevo.titulo_pagina' => 'Afegir manteniment',
    'garaje.mantenimiento.nuevo.titulo' => 'Afegir manteniment',
    'garaje.mantenimiento.editar.titulo_pagina' => 'Editar manteniment',
    'garaje.mantenimiento.editar.titulo' => 'Editar manteniment',

    'garaje.mantenimiento.vehiculo' => 'Vehicle',
    'garaje.mantenimiento.fecha' => 'Data',
    'garaje.mantenimiento.tipo' => 'Tipus',
    'garaje.mantenimiento.descripcion' => 'Descripció',
    'garaje.mantenimiento.kilometros' => 'Quilòmetres',
    'garaje.mantenimiento.coste' => 'Cost',
    'garaje.mantenimiento.volver' => 'Tornar',
    'garaje.mantenimiento.guardar' => 'Guardar manteniment',
    'garaje.mantenimiento.guardar_cambios' => 'Guardar canvis',

    // garatge - missatges manteniment
    'garaje.mantenimiento.error.vehiculo_no_valido' => 'Vehicle no vàlid',
    'garaje.mantenimiento.error.vehiculo_no_encontrado' => 'Vehicle no trobat o sense permisos',
    'garaje.mantenimiento.error.fecha_tipo_obligatorios' => 'La data i el tipus són obligatoris',
    'garaje.mantenimiento.error.fecha_no_valida' => 'La data no és vàlida',
    'garaje.mantenimiento.error.tipo_maximo' => 'El tipus no pot superar els 100 caràcters',
    'garaje.mantenimiento.error.kilometros_entero' => 'Els quilòmetres han de ser un número enter positiu',
    'garaje.mantenimiento.error.coste_valido' => 'El cost ha de ser un número vàlid major o igual que zero',
    'garaje.mantenimiento.error.guardar' => 'No s’ha pogut guardar el manteniment',
    'garaje.mantenimiento.ok.guardar' => 'Manteniment afegit correctament',

    'garaje.mantenimiento.error.mantenimiento_no_valido' => 'Manteniment no vàlid',
    'garaje.mantenimiento.error.mantenimiento_no_encontrado' => 'Manteniment no trobat o sense permisos',
    'garaje.mantenimiento.error.actualizar' => 'No s’ha pogut actualitzar el manteniment',
    'garaje.mantenimiento.ok.actualizar' => 'Manteniment actualitzat correctament',
    'garaje.mantenimiento.error.eliminar' => 'No s’ha pogut eliminar el manteniment',
    'garaje.mantenimiento.ok.eliminar' => 'Manteniment eliminat correctament',

    // comunitat - llistat
    'comunidad.index.titulo_pagina' => 'Comunitat',
    'comunidad.index.titulo' => 'Comunitat',
    'comunidad.index.crear_publicacion' => 'Crear publicació',
    'comunidad.index.buscar_publicaciones' => 'Cercar publicacions',
    'comunidad.index.placeholder_busqueda' => 'Contingut o autor',
    'comunidad.index.ordenar_por' => 'Ordenar per',
    'comunidad.index.orden.recientes' => 'Més recents',
    'comunidad.index.orden.antiguas' => 'Més antigues',
    'comunidad.index.orden.likes' => 'Més m’agrada',
    'comunidad.index.orden.comentarios' => 'Més comentaris',
    'comunidad.index.aplicar_filtros' => 'Aplicar filtres',
    'comunidad.index.limpiar' => 'Netejar',
    'comunidad.index.sin_publicaciones' => 'No s’han trobat publicacions',
    'comunidad.index.por' => 'per',
    'comunidad.index.alt_imagen_publicacion' => 'Imatge de la publicació',
    'comunidad.index.comentario_singular' => 'comentari',
    'comunidad.index.comentario_plural' => 'comentaris',
    'comunidad.index.like_singular' => 'm’agrada',
    'comunidad.index.like_plural' => 'm’agrada',
    'comunidad.index.dar_like' => 'Donar m’agrada',
    'comunidad.index.quitar_like' => 'Treure m’agrada',
    'comunidad.index.ver_publicacion' => 'Veure publicació',
    'comunidad.index.editar_publicacion' => 'Editar publicació',
    'comunidad.index.eliminar_publicacion' => 'Eliminar publicació',
    'comunidad.index.confirmar_eliminar_publicacion' => 'Segur que vols eliminar aquesta publicació?',
    'comunidad.index.publicacion_encontrada' => 'publicació trobada',
    'comunidad.index.publicaciones_encontradas' => 'publicacions trobades',
    'comunidad.index.paginacion_aria' => 'Paginació de publicacions',
    'comunidad.index.pagina_de' => 'Pàgina {actual} de {total}',
    'comunidad.index.anterior' => 'Anterior',
    'comunidad.index.siguiente' => 'Següent',

    // comunitat - detall
    'comunidad.detalle.titulo_pagina' => 'Detall de publicació',
    'comunidad.detalle.titulo' => 'Detall de publicació',
    'comunidad.detalle.error.cargar' => 'No s’ha pogut carregar la publicació',
    'comunidad.detalle.anadir_comentario' => 'Afegir comentari',
    'comunidad.detalle.comentario' => 'Comentari',
    'comunidad.detalle.publicar_comentario' => 'Publicar comentari',
    'comunidad.detalle.comentarios' => 'Comentaris',
    'comunidad.detalle.sin_comentarios' => 'Encara no hi ha comentaris en aquesta publicació',
    'comunidad.detalle.editar_comentario' => 'Editar comentari',
    'comunidad.detalle.eliminar_comentario' => 'Eliminar comentari',
    'comunidad.detalle.confirmar_eliminar_comentario' => 'Segur que vols eliminar aquest comentari?',
    'comunidad.detalle.responder' => 'Respondre',
    'comunidad.detalle.tu_respuesta' => 'La teva resposta',
    'comunidad.detalle.publicar_respuesta' => 'Publicar resposta',
    'comunidad.detalle.ver_una_respuesta' => 'Veure 1 resposta',
    'comunidad.detalle.ver_respuestas' => 'Veure {total} respostes',
    'comunidad.detalle.ocultar_respuestas' => 'Amagar respostes',
    'comunidad.detalle.cargando_respuestas' => 'Carregant respostes...',
    'comunidad.detalle.error_cargar_respuestas' => 'No s’han pogut carregar les respostes',
    'comunidad.detalle.sin_respuestas' => 'No hi ha respostes',
    'comunidad.detalle.volver' => 'Tornar a comunitat',

    // comunitat - formularis
    'comunidad.form.nueva.titulo_pagina' => 'Crear publicació',
    'comunidad.form.nueva.titulo' => 'Crear publicació',
    'comunidad.form.contenido' => 'Contingut',
    'comunidad.form.imagen_opcional' => 'Imatge opcional',
    'comunidad.form.publicar' => 'Publicar',
    'comunidad.form.volver_comunidad' => 'Tornar a comunitat',

    'comunidad.form.editar.titulo_pagina' => 'Editar publicació',
    'comunidad.form.editar.titulo' => 'Editar publicació',
    'comunidad.form.editar.error_cargar' => 'No s’ha pogut carregar la publicació',
    'comunidad.form.imagen_actual' => 'Imatge actual',
    'comunidad.form.alt_imagen_actual' => 'Imatge actual de la publicació',
    'comunidad.form.nueva_imagen_opcional' => 'Nova imatge opcional',
    'comunidad.form.guardar_cambios' => 'Guardar canvis',
    'comunidad.form.volver_publicacion' => 'Tornar a la publicació',

    'comunidad.form.editar_comentario.titulo_pagina' => 'Editar comentari',
    'comunidad.form.editar_comentario.titulo' => 'Editar comentari',
    'comunidad.form.editar_comentario.error_cargar' => 'No s’ha pogut carregar el comentari',
    'comunidad.form.editar_comentario.comentario' => 'Comentari',

    // comunitat - missatges backend/ajax
    'comunidad.error.contenido_obligatorio' => 'El contingut és obligatori',
    'comunidad.error.imagen_formato' => 'Format d’imatge no permès',
    'comunidad.error.guardar_publicacion' => 'No s’ha pogut guardar la publicació',
    'comunidad.ok.publicacion_creada' => 'Publicació creada correctament',
    'comunidad.error.publicacion_no_valida' => 'Publicació no vàlida',
    'comunidad.error.publicacion_no_existe' => 'La publicació no existeix',
    'comunidad.error.datos_respuesta_no_validos' => 'Dades de resposta no vàlides',
    'comunidad.error.comentario_responder_no_valido' => 'El comentari al qual intentes respondre no és vàlid',
    'comunidad.error.respuesta_vacia' => 'La resposta no pot estar buida',
    'comunidad.error.guardar_respuesta' => 'No s’ha pogut guardar la resposta',
    'comunidad.ok.respuesta_publicada' => 'Resposta publicada correctament',
    'comunidad.error.comentario_vacio' => 'El comentari no pot estar buit',
    'comunidad.error.guardar_comentario' => 'No s’ha pogut guardar el comentari',
    'comunidad.ok.comentario_publicado' => 'Comentari publicat correctament',
    'comunidad.error.like_actualizar' => 'No s’ha pogut actualitzar el m’agrada',
    'comunidad.error.sin_permiso_editar_publicacion' => 'No tens permís per editar aquesta publicació',
    'comunidad.error.sin_permiso_eliminar_publicacion' => 'No tens permís per eliminar aquesta publicació',
    'comunidad.error.eliminar_publicacion' => 'No s’ha pogut eliminar la publicació',
    'comunidad.ok.publicacion_eliminada' => 'Publicació eliminada correctament',
    'comunidad.error.datos_no_validos' => 'Dades no vàlides',
    'comunidad.error.comentario_no_valido' => 'El comentari no és vàlid',

    // perfil
    'perfil.error.cargar' => 'No s’ha pogut carregar el perfil',
    'perfil.error.no_valido' => 'Perfil no vàlid',
    'perfil.error.no_existe' => 'El perfil no existeix',
    'perfil.error.usuario_no_encontrado' => 'Usuari no trobat',
    'perfil.error.imagen_obligatoria' => 'Has de seleccionar una imatge',
    'perfil.error.subir_foto' => 'No s’ha pogut pujar la foto de perfil',
    'perfil.error.archivo_no_valido' => 'El fitxer pujat no és vàlid',
    'perfil.error.imagen_tamanyo' => 'La imatge no pot superar els 3 MB',
    'perfil.error.imagen_formato' => 'Només es permeten imatges JPG, PNG o WEBP',
    'perfil.error.crear_directorio' => 'No s’ha pogut crear el directori de fotos de perfil',
    'perfil.error.guardar_foto' => 'No s’ha pogut guardar la foto de perfil',
    'perfil.ok.foto_actualizada' => 'Foto de perfil actualitzada',
    'perfil.error.campos_obligatorios' => 'Tots els camps són obligatoris',
    'perfil.error.nombre_reglas' => 'El nom d’usuari no compleix les regles permeses',
    'perfil.error.email_no_valido' => 'El correu electrònic no és vàlid',
    'perfil.error.nombre_en_uso' => 'El nom d’usuari ja està en ús',
    'perfil.error.email_en_uso' => 'El correu electrònic ja està en ús',
    'perfil.ok.actualizado' => 'Perfil actualitzat correctament',
    'perfil.error.password_obligatoria' => 'Tots els camps de contrasenya són obligatoris',
    'perfil.error.password_actual' => 'La contrasenya actual no és correcta',
    'perfil.error.password_no_coincide' => 'Les noves contrasenyes no coincideixen',
    'perfil.error.password_requisitos' => 'La nova contrasenya ha de tenir mínim 8 caràcters, una majúscula, una minúscula i un número',
    'perfil.error.password_igual' => 'La nova contrasenya no pot ser igual que l’actual',
    'perfil.ok.password_actualizada' => 'Contrasenya actualitzada correctament',

    'perfil.ver.titulo_pagina' => 'Perfil',
    'perfil.ver.titulo_de' => 'Perfil de',
    'perfil.ver.alt_foto' => 'Foto de perfil de',
    'perfil.ver.sin_foto' => 'Sense foto',
    'perfil.ver.cambiar_foto' => 'Canviar foto de perfil',
    'perfil.ver.nueva_foto' => 'Nova foto',
    'perfil.ver.actualizar_foto' => 'Actualitzar foto',
    'perfil.ver.editar_datos' => 'Editar dades del perfil',
    'perfil.ver.nombre_usuario' => 'Nom d’usuari',
    'perfil.ver.email' => 'Correu electrònic',
    'perfil.ver.guardar_cambios' => 'Guardar canvis',
    'perfil.ver.cambiar_password' => 'Canviar contrasenya',
    'perfil.ver.password_actual' => 'Contrasenya actual',
    'perfil.ver.password_nueva' => 'Nova contrasenya',
    'perfil.ver.password_nueva_repetida' => 'Repetir nova contrasenya',
    'perfil.ver.garaje_publico' => 'Garatge públic',
    'perfil.ver.sin_vehiculos' => 'Aquest usuari encara no té vehicles al seu garatge',
    'perfil.ver.sin_imagen' => 'Sense imatge',
    'perfil.ver.alt_vehiculo' => 'Imatge de',
    'perfil.ver.ver_detalles' => 'Veure detalls',
    'perfil.ver.publicaciones' => 'Publicacions',
    'perfil.ver.sin_publicaciones' => 'Aquest usuari encara no té publicacions',
    'perfil.ver.alt_publicacion' => 'Imatge de la publicació',
    'perfil.ver.comentario_singular' => 'comentari',
    'perfil.ver.comentario_plural' => 'comentaris',
    'perfil.ver.like_singular' => 'm’agrada',
    'perfil.ver.like_plural' => 'm’agrada',
    'perfil.ver.ver_publicacion' => 'Veure publicació',

    // perfil - vehicle públic
    'perfil.vehiculo.error.cargar' => 'No s’ha pogut carregar el vehicle',
    'perfil.vehiculo.error.no_valido' => 'Vehicle no vàlid',
    'perfil.vehiculo.error.no_existe' => 'El vehicle no existeix',
    'perfil.vehiculo.titulo_pagina' => 'Vehicle públic',
    'perfil.vehiculo.propietario' => 'Propietari',
    'perfil.vehiculo.alt_imagen' => 'Imatge del vehicle',
    'perfil.vehiculo.detalles_publicos' => 'Detalls públics',
    'perfil.vehiculo.any' => 'Any',
    'perfil.vehiculo.carroceria' => 'Carrosseria',
    'perfil.vehiculo.combustible' => 'Combustible',
    'perfil.vehiculo.cambio' => 'Canvi',
    'perfil.vehiculo.potencia' => 'Potència',
    'perfil.vehiculo.cilindrada' => 'Cilindrada',
    'perfil.vehiculo.volver_perfil' => 'Tornar al perfil',
];
