<?php

return [
    // navabar
    'navbar.inicio' => 'Inici',
    'navbar.login' => 'Iniciar sessió',
    'navbar.registro' => 'Registrar-se',
    'navbar.garaje' => 'El meu garatge',
    'navbar.comunidad' => 'Comunitat',
    'navbar.diagnostico' => 'Diagnòstic',
    'navbar.perfil' => 'El meu perfil',
    'navbar.admin' => 'Panell d’administració',
    'navbar.logout' => 'Tancar sessió',

    'navbar.idioma_es' => 'ES',
    'navbar.idioma_ca' => 'CA',
    'navbar.cambiar_idioma' => 'Canviar idioma',
    'navbar.navegacion_principal' => 'Navegació principal',
    'navbar.abrir_menu' => 'Obrir menú',
    'navbar.cerrar_menu' => 'Tancar menú',

    'idioma.ok.cambiado' => 'Idioma actualitzat correctament',

    // seguretat
    'seguridad.error.csrf' => 'La sessió de seguretat ha caducat. Recarrega la pàgina i torna-ho a intentar',
    'seguridad.error.servidor' => 'S’ha produït un error intern. Torna-ho a intentar més tard',
    'seguridad.error.ruta_no_encontrada' => 'Pàgina no trobada',

    'error.403.titulo' => 'Accés denegat',
    'error.403.detalle' => 'No tens permisos per accedir a aquesta zona o l’acció sol·licitada no és vàlida',
    'error.404.titulo' => 'Pàgina no trobada',
    'error.404.detalle' => 'La ruta que estàs intentant obrir no existeix o ha canviat d’ubicació',
    'error.500.titulo' => 'Error intern',
    'error.500.mensaje' => 'S’ha produït un error intern. Torna-ho a intentar més tard',
    'error.500.detalle' => 'L’equip tècnic pot revisar els logs del servidor per localitzar el problema',
    'error.descripcion.generica' => 'Pots tornar a l’inici o continuar navegant per TorqHub',
    'error.boton.inicio' => 'Tornar a l’inici',
    'error.boton.garaje' => 'Anar al meu garatge',
    'error.boton.login' => 'Iniciar sessió',

    // auth - login
    'auth.login.titulo_pagina' => 'Iniciar sessió',
    'auth.login.titulo' => 'Iniciar sessió',
    'auth.login.email' => 'Correu electrònic',
    'auth.login.password' => 'Contrasenya',
    'auth.login.boton' => 'Entrar',
    'auth.login.password_olvidada' => 'He oblidat la contrasenya',

    // auth - registro
    'auth.registro.titulo_pagina' => 'Registrar-se',
    'auth.registro.titulo' => 'Registrar-se',
    'auth.registro.nombre' => 'Nom d’usuari',
    'auth.registro.nombre_ayuda' => 'Només lletres minúscules, números, punts i guions baixos, sense espais, sense punts consecutius i sense acabar en punt',
    'auth.registro.email' => 'Correu electrònic',
    'auth.registro.password' => 'Contrasenya',
    'auth.registro.password_repetida' => 'Repetir contrasenya',
    'auth.registro.password_ayuda' => 'Mínim 8 caràcters, una majúscula, una minúscula i un número',
    'auth.registro.error_password_repetida' => 'Les contrasenyes no coincideixen',
    'auth.registro.boton' => 'Crear compte',

    // auth - recuperación
    'auth.password_olvidada.titulo_pagina' => 'Recuperar contrasenya',
    'auth.password_olvidada.titulo' => 'Recuperar contrasenya',
    'auth.password_olvidada.email' => 'Correu electrònic',
    'auth.password_olvidada.boton' => 'Enviar enllaç de recuperació',
    'auth.password_olvidada.volver_login' => 'Tornar a iniciar sessió',

    // auth - restablecer contraseña
    'auth.password_restablecer.titulo_pagina' => 'Restablir contrasenya',
    'auth.password_restablecer.titulo' => 'Restablir contrasenya',
    'auth.password_restablecer.password' => 'Nova contrasenya',
    'auth.password_restablecer.password_repetida' => 'Repetir contrasenya',
    'auth.password_restablecer.boton' => 'Guardar nova contrasenya',

    // auth - mensajes
    'auth.error.rellena_login' => 'Omple el correu electrònic i la contrasenya',
    'auth.error.servidor' => 'Error de servidor, intenta-ho més tard',
    'auth.error.credenciales' => 'Credencials incorrectes',
    'auth.ok.sesion_iniciada' => 'Sessió iniciada',
    'auth.ok.sesion_cerrada' => 'Sessió tancada correctament',

    'auth.error.registro_obligatorios' => 'Has d’omplir el nom d’usuari, el correu electrònic i la contrasenya',
    'auth.error.password_no_coincide' => 'Les contrasenyes no coincideixen',
    'auth.error.nombre_requisitos' => 'El nom d’usuari només pot contenir lletres minúscules, números, punts i guions baixos, sense espais, sense punts consecutius i sense acabar en punt',
    'auth.error.password_requisitos' => 'La contrasenya ha de tenir mínim 8 caràcters, una majúscula, una minúscula i un número',
    'auth.error.nombre_uso' => 'Aquest nom d’usuari ja està en ús',
    'auth.error.email_registrado' => 'Aquest correu electrònic ja està registrat',
    'auth.ok.registro_completado' => 'Registre completat, ara inicia sessió',
    'auth.error.nombre_email_uso' => 'El nom d’usuari o el correu electrònic ja estan en ús',
    'auth.error.registro_error' => 'S’ha produït un error en registrar el compte',

    'auth.error.email_no_valido' => 'El correu electrònic no és vàlid',
    'auth.ok.recuperacion_enviada' => 'Si el correu existeix, rebràs un enllaç per restablir la contrasenya',
    'auth.error.token_no_valido' => 'Token no vàlid',
    'auth.error.enlace_expirado' => 'L’enllaç ja no és vàlid o ha caducat',
    'auth.error.enlace_restablecer_no_valido' => 'L’enllaç per restablir la contrasenya no és vàlid',
    'auth.error.campos_obligatorios' => 'Tots els camps són obligatoris',
    'auth.error.password_minimos' => 'La contrasenya no compleix els requisits mínims',
    'auth.ok.password_restablecida' => 'Contrasenya restablerta correctament',
    'auth.error.usuario_desactivado' => 'El teu compte està desactivat',

    // inici
    'inicio.titulo_pagina' => 'Inici',
    'inicio.titulo' => 'Inici',
    'inicio.saludo' => 'Hola',
    'inicio.bienvenida' => 'Benvingut a TorqHub',

    'inicio.publico.etiqueta' => 'Projecte final de Desenvolupament d’Aplicacions Web',
    'inicio.publico.titulo' => 'TorqHub',
    'inicio.publico.descripcion' => 'Una plataforma web per a aficionats al motor amb garatge virtual, comunitat, perfils i diagnòstic mecànic assistit mitjançant un sistema expert propi.',
    'inicio.publico.login' => 'Iniciar sessió',
    'inicio.publico.registro' => 'Crear compte',

    'inicio.publico.panel.etiqueta' => 'Base tècnica',
    'inicio.publico.panel.titulo' => 'Projecte desenvolupat des de zero',
    'inicio.publico.panel.descripcion' => 'TorqHub està construït amb PHP, MySQL i una arquitectura MVC pròpia, prioritzant seguretat, organització i funcionalitats defensables.',
    'inicio.publico.panel.mvc' => 'Arquitectura MVC pròpia en PHP',
    'inicio.publico.panel.seguridad' => 'Sessions, rols, CSRF i validacions',
    'inicio.publico.panel.multilenguaje' => 'Interfície multillenguatge en espanyol i català',

    'inicio.publico.funcionalidades' => 'Funcionalitats principals',
    'inicio.publico.funcionalidades.descripcion' => 'L’aplicació reuneix mòduls connectats entre si per simular una plataforma social i tècnica centrada en vehicles.',

    'inicio.publico.garaje.etiqueta' => 'Garatge',
    'inicio.publico.garaje.titulo' => 'Garatge virtual',
    'inicio.publico.garaje.descripcion' => 'Permet registrar vehicles, fotos, dades tècniques, historial de manteniments i consultes VIN.',

    'inicio.publico.comunidad.etiqueta' => 'Social',
    'inicio.publico.comunidad.titulo' => 'Comunitat',
    'inicio.publico.comunidad.descripcion' => 'Els usuaris poden crear publicacions, comentar, respondre i donar likes mitjançant AJAX.',

    'inicio.publico.diagnostico.etiqueta' => 'IA',
    'inicio.publico.diagnostico.titulo' => 'Diagnòstic assistit',
    'inicio.publico.diagnostico.descripcion' => 'Sistema expert basat en regles, causes i paraules clau administrables des del panell privat.',

    'inicio.publico.perfiles.etiqueta' => 'Usuaris',
    'inicio.publico.perfiles.titulo' => 'Perfils',
    'inicio.publico.perfiles.descripcion' => 'Cada usuari disposa de perfil públic amb publicacions, foto, dades editables i vehicles visibles.',

    'inicio.dashboard.etiqueta' => 'Panell privat',
    'inicio.dashboard.titulo' => 'Hola',
    'inicio.dashboard.descripcion' => 'Des d’aquí pots accedir ràpidament a les parts principals de TorqHub i continuar treballant amb el teu garatge, comunitat i diagnòstic.',
    'inicio.dashboard.accion_garaje' => 'Veure el meu garatge',
    'inicio.dashboard.accion_publicacion' => 'Crear publicació',

    'inicio.dashboard.panel.etiqueta' => 'Resum del projecte',
    'inicio.dashboard.panel.titulo' => 'Zona d’usuari',
    'inicio.dashboard.panel.descripcion' => 'Aquest panell centralitza els mòduls principals sense duplicar funcionalitats ja existents.',
    'inicio.dashboard.panel.garaje' => 'Gestiona els teus vehicles i manteniments',
    'inicio.dashboard.panel.comunidad' => 'Participa en la comunitat',
    'inicio.dashboard.panel.diagnostico' => 'Consulta el diagnòstic assistit',

    'inicio.dashboard.resumen' => 'Resum ràpid',
    'inicio.dashboard.resumen_descripcion' => 'Aquestes dades es calculen des de la base de dades i resumeixen la teva activitat principal dins de TorqHub.',
    'inicio.dashboard.vehiculos.etiqueta' => 'Garatge',
    'inicio.dashboard.vehiculos.titulo' => 'Vehicles',
    'inicio.dashboard.vehiculos.descripcion' => 'Accedeix al llistat dels teus vehicles i consulta’n els detalls.',

    'inicio.dashboard.mantenimientos.etiqueta' => 'Historial',
    'inicio.dashboard.mantenimientos.titulo' => 'Manteniments',
    'inicio.dashboard.mantenimientos.descripcion' => 'Revisa l’historial tècnic des del detall de cada vehicle.',

    'inicio.dashboard.publicaciones.etiqueta' => 'Comunitat',
    'inicio.dashboard.publicaciones.titulo' => 'Publicacions',
    'inicio.dashboard.publicaciones.descripcion' => 'Consulta publicacions, comentaris, respostes i likes.',

    'inicio.dashboard.diagnostico.etiqueta' => 'Assistent',
    'inicio.dashboard.diagnostico.titulo' => 'Diagnòstic assistit',
    'inicio.dashboard.diagnostico.descripcion' => 'Descriu símptomes del vehicle i rep possibles causes ordenades per coincidència.',

    'inicio.dashboard.acciones' => 'Accions ràpides',
    'inicio.dashboard.acciones_descripcion' => 'Dreceres directes a les accions més habituals dins de l’aplicació.',

    'inicio.dashboard.accion.anadir_vehiculo' => 'Afegir vehicle',
    'inicio.dashboard.accion.anadir_vehiculo.descripcion' => 'Registra un nou vehicle al teu garatge virtual.',

    'inicio.dashboard.accion.crear_publicacion' => 'Crear publicació',
    'inicio.dashboard.accion.crear_publicacion.descripcion' => 'Comparteix una actualització amb la comunitat.',

    'inicio.dashboard.accion.hacer_diagnostico' => 'Fer diagnòstic',
    'inicio.dashboard.accion.hacer_diagnostico.descripcion' => 'Obre l’assistent de diagnòstic mecànic.',

    'inicio.dashboard.accion.ver_perfil' => 'Veure el meu perfil',
    'inicio.dashboard.accion.ver_perfil.descripcion' => 'Consulta el teu perfil públic i les teves publicacions.',
    'inicio.dashboard.likes.etiqueta' => 'Interacció',
    'inicio.dashboard.likes.titulo' => 'Likes rebuts',
    'inicio.dashboard.likes.descripcion' => 'Likes acumulats a les teves publicacions de la comunitat.',

    'inicio.dashboard.actividad' => 'Activitat recent',
    'inicio.dashboard.actividad.descripcion' => 'Últims elements registrats als teus mòduls principals per continuar ràpidament on ho vas deixar.',
    'inicio.dashboard.actividad.ver_todo' => 'Veure-ho tot',
    'inicio.dashboard.actividad.sin_fecha' => 'Sense data',

    'inicio.dashboard.actividad.vehiculos' => 'Últims vehicles',
    'inicio.dashboard.actividad.vehiculos.vacio' => 'Encara no has afegit vehicles.',

    'inicio.dashboard.actividad.mantenimientos' => 'Últims manteniments',
    'inicio.dashboard.actividad.mantenimientos.vacio' => 'Encara no has registrat manteniments.',

    'inicio.dashboard.actividad.publicaciones' => 'Últimes publicacions',
    'inicio.dashboard.actividad.publicaciones.vacio' => 'Encara no has creat publicacions.',

    'inicio.dashboard.actividad.likes' => 'likes',
    'inicio.dashboard.actividad.comentarios' => 'comentaris',

    // garatge - llistat
    'garaje.index.titulo_pagina' => 'El meu garatge',
    'garaje.index.titulo' => 'El meu garatge',
    'garaje.index.anadir_vehiculo' => '+ Afegir vehicle',
    'garaje.index.sin_vehiculos' => 'Encara no tens vehicles',
    'garaje.index.ver' => 'Veure',
    'garaje.index.editar' => 'Editar',
    'garaje.index.eliminar' => 'Eliminar',
    'garaje.index.alt_imagen_vehiculo' => 'Imatge del vehicle',
    'garaje.index.imagen_no_disponible' => 'Sense imatge',

    // garatge - formulari vehicle
    'garaje.form.nuevo.titulo_pagina' => 'Afegir vehicle',
    'garaje.form.nuevo.titulo' => 'Afegir vehicle',
    'garaje.form.editar.titulo_pagina' => 'Editar vehicle',
    'garaje.form.editar.titulo' => 'Editar vehicle',

    'garaje.form.error.cargar_editar' => 'No s’ha pogut carregar el vehicle per editar',

    'garaje.form.marca' => 'Marca',
    'garaje.form.modelo' => 'Model',
    'garaje.form.any' => 'Any',
    'garaje.form.vin_opcional' => 'VIN',
    'garaje.form.vin' => 'VIN',
    'garaje.form.consultar_vin' => 'Consultar VIN',
    'garaje.form.vin_ayuda_nuevo' => 'Introdueix un VIN real de 17 caràcters per autocompletar dades del vehicle',
    'garaje.form.vin_ayuda_editar' => 'Si consultes el VIN, s’intentaran autocompletar les dades disponibles',

    'garaje.form.carroceria' => 'Carrosseria',
    'garaje.form.tipo_combustible' => 'Tipus de combustible',
    'garaje.form.tipo_cambio' => 'Tipus de canvi',
    'garaje.form.selecciona_opcion' => 'Selecciona una opció',

    'garaje.form.potencia_cv' => 'Potència (CV)',
    'garaje.form.cilindrada_cm3' => 'Cilindrada (cm³)',

    'garaje.form.imagen' => 'Fotos del vehicle',
    'garaje.form.imagen_ayuda_nuevo' => 'Pots pujar fins a 8 fotos. Formats permesos: JPG, PNG o WEBP. Màxim 3 MB per foto',
    'garaje.form.cambiar_imagen' => 'Afegir fotos del vehicle',
    'garaje.form.cambiar_imagen_ayuda' => 'Les noves fotos s’afegiran a l’àlbum actual. Màxim 8 fotos per pujada i 3 MB per foto',
    'garaje.form.imagen_actual' => 'Fotos actuals',
    'garaje.form.alt_imagen_actual' => 'Imatge actual del vehicle',

    'garaje.form.cancelar' => 'Cancel·lar',
    'garaje.form.guardar_vehiculo' => 'Guardar vehicle',
    'garaje.form.guardar_cambios' => 'Guardar canvis',

    // garatge - missatges javascript
    'garaje.js.campo.marca' => 'la marca',
    'garaje.js.campo.modelo' => 'el model',
    'garaje.js.campo.any' => 'l’any',
    'garaje.js.campo.vin' => 'el VIN',
    'garaje.js.campo.carroceria' => 'la carrosseria',
    'garaje.js.campo.tipo_combustible' => 'el tipus de combustible',
    'garaje.js.campo.tipo_cambio' => 'el tipus de canvi',
    'garaje.js.campo.potencia_cv' => 'la potència',
    'garaje.js.campo.cilindrada_cm3' => 'la cilindrada',
    'garaje.js.campo.imagen' => 'la imatge',
    'garaje.js.campo.imagenes' => 'les fotos',
    'garaje.js.campo.este_campo' => 'aquest camp',

    'garaje.js.error.falta' => 'Falta {campo}',
    'garaje.js.error.any_rango' => 'L’any ha d’estar entre {minimo} i {maximo}',
    'garaje.js.error.potencia_entero' => 'La potència ha de ser un número enter positiu',
    'garaje.js.error.cilindrada_entero' => 'La cilindrada ha de ser un número enter positiu',
    'garaje.js.error.imagen_tipo' => 'Només es permeten imatges JPG, PNG o WEBP',
    'garaje.js.error.imagen_tamanyo' => 'La imatge no pot superar els 3 MB',
    'garaje.js.error.imagenes_limite' => 'Pots pujar un màxim de 8 fotos alhora',

    'garaje.js.vin.no_preparar' => 'No s’ha pogut preparar la consulta VIN',
    'garaje.js.vin.introduce' => 'Introdueix un VIN abans de consultar',
    'garaje.js.vin.formato' => 'El VIN ha de tenir 17 caràcters i no pot contenir I, O ni Q',
    'garaje.js.vin.consultando_boton' => 'Consultant...',
    'garaje.js.vin.consultando_mensaje' => 'Consultant VIN...',
    'garaje.js.vin.respuesta_no_json' => 'La resposta del servidor no és JSON vàlid',
    'garaje.js.vin.no_consultar' => 'No s’ha pogut consultar el VIN',
    'garaje.js.vin.origen_cache' => 'memòria cau local',
    'garaje.js.vin.origen_api' => 'API externa',
    'garaje.js.vin.ok_desde' => 'VIN consultat correctament des de {origen}',

    // garatge - detall vehicle
    'garaje.detalle.titulo_pagina' => 'Detall del vehicle',
    'garaje.detalle.titulo' => 'Detall del vehicle',
    'garaje.detalle.error.cargar' => 'No s’ha pogut carregar el vehicle',
    'garaje.detalle.alt_imagen' => 'Imatge del vehicle',
    'garaje.detalle.imagen_no_disponible' => 'Imatge no disponible',
    'garaje.detalle.imagen_ayuda' => 'Encara no s’ha pujat cap foto per a aquest vehicle',
    'garaje.detalle.galeria' => 'Galeria de fotos del vehicle',
    'garaje.detalle.foto_anterior' => 'Veure foto anterior',
    'garaje.detalle.foto_siguiente' => 'Veure foto següent',
    'garaje.detalle.foto_contador' => 'Foto',
    'garaje.detalle.subtitulo' => 'Vehicle registrat al teu garatge',
    'garaje.detalle.volver_garaje' => 'Tornar al garatge',
    'garaje.detalle.editar' => 'Editar',
    'garaje.detalle.eliminar' => 'Eliminar',
    'garaje.detalle.estadisticas' => 'Estadístiques ràpides',
    'garaje.detalle.total_gastado' => 'Total gastat',
    'garaje.detalle.mantenimientos' => 'Manteniments',
    'garaje.detalle.ultimo_mantenimiento' => 'Últim manteniment',
    'garaje.detalle.sin_registros' => 'Sense registres',
    'garaje.detalle.no_indicado' => 'No indicat',
    'garaje.detalle.marca' => 'Marca',
    'garaje.detalle.modelo' => 'Model',
    'garaje.detalle.any' => 'Any',
    'garaje.detalle.vin' => 'VIN',
    'garaje.detalle.carroceria' => 'Carrosseria',
    'garaje.detalle.tipo_combustible' => 'Tipus de combustible',
    'garaje.detalle.tipo_cambio' => 'Tipus de canvi',
    'garaje.detalle.potencia' => 'Potència',
    'garaje.detalle.cilindrada' => 'Cilindrada',
    'garaje.detalle.fecha_alta' => 'Data d’alta',

    // garatge - historial
    'garaje.historial.titulo' => 'Historial de manteniment',
    'garaje.historial.anadir' => 'Afegir manteniment',
    'garaje.historial.exportar_csv' => 'Exportar CSV',
    'garaje.historial.tipo' => 'Tipus',
    'garaje.historial.todos' => 'Tots',
    'garaje.historial.fecha_desde' => 'Data des de',
    'garaje.historial.fecha_hasta' => 'Data fins a',
    'garaje.historial.km_minimos' => 'Km mínims',
    'garaje.historial.km_maximos' => 'Km màxims',
    'garaje.historial.coste_minimo' => 'Cost mínim',
    'garaje.historial.coste_maximo' => 'Cost màxim',
    'garaje.historial.ordenar_por' => 'Ordenar per',
    'garaje.historial.fecha' => 'Data',
    'garaje.historial.kilometros' => 'Quilòmetres',
    'garaje.historial.coste' => 'Cost',
    'garaje.historial.direccion' => 'Direcció',
    'garaje.historial.descendente' => 'Descendent',
    'garaje.historial.ascendente' => 'Ascendent',
    'garaje.historial.filtrar' => 'Filtrar',
    'garaje.historial.limpiar' => 'Netejar',
    'garaje.historial.error_ajax' => 'No s’ha pogut actualitzar l’historial',
    'garaje.historial.total_visibles' => 'Total visibles',
    'garaje.historial.coste_total_visible' => 'Cost total visible',
    'garaje.historial.primer_resultado' => 'Primer resultat',
    'garaje.historial.sin_resultados' => 'Sense resultats',
    'garaje.historial.anterior' => 'Anterior',
    'garaje.historial.siguiente' => 'Següent',
    'garaje.historial.sin_mantenimientos' => 'No hi ha manteniments que coincideixin amb els filtres aplicats',
    'garaje.historial.descripcion' => 'Descripció',
    'garaje.historial.acciones' => 'Accions',
    'garaje.historial.no_indicada' => 'No indicada',
    'garaje.historial.no_indicados' => 'No indicats',
    'garaje.historial.editar' => 'Editar',
    'garaje.historial.eliminar' => 'Eliminar',
    'garaje.historial.confirmar_eliminar' => 'Segur que vols eliminar aquest manteniment?',

    // garatge - formulari manteniment
    'garaje.mantenimiento.nuevo.titulo_pagina' => 'Afegir manteniment',
    'garaje.mantenimiento.nuevo.titulo' => 'Afegir manteniment',
    'garaje.mantenimiento.editar.titulo_pagina' => 'Editar manteniment',
    'garaje.mantenimiento.editar.titulo' => 'Editar manteniment',

    'garaje.mantenimiento.vehiculo' => 'Vehicle',
    'garaje.mantenimiento.fecha' => 'Data',
    'garaje.mantenimiento.tipo' => 'Tipus',
    'garaje.mantenimiento.descripcion' => 'Descripció',
    'garaje.mantenimiento.kilometros' => 'Quilòmetres',
    'garaje.mantenimiento.coste' => 'Cost',
    'garaje.mantenimiento.volver' => 'Tornar',
    'garaje.mantenimiento.guardar' => 'Guardar manteniment',
    'garaje.mantenimiento.guardar_cambios' => 'Guardar canvis',

    // garatge - missatges manteniment
    'garaje.mantenimiento.error.vehiculo_no_valido' => 'Vehicle no vàlid',
    'garaje.mantenimiento.error.vehiculo_no_encontrado' => 'Vehicle no trobat o sense permisos',
    'garaje.mantenimiento.error.fecha_tipo_obligatorios' => 'La data i el tipus són obligatoris',
    'garaje.mantenimiento.error.fecha_no_valida' => 'La data no és vàlida',
    'garaje.mantenimiento.error.tipo_maximo' => 'El tipus no pot superar els 100 caràcters',
    'garaje.mantenimiento.error.kilometros_entero' => 'Els quilòmetres han de ser un número enter positiu',
    'garaje.mantenimiento.error.coste_valido' => 'El cost ha de ser un número vàlid major o igual que zero',
    'garaje.mantenimiento.error.guardar' => 'No s’ha pogut guardar el manteniment',
    'garaje.mantenimiento.ok.guardar' => 'Manteniment afegit correctament',

    'garaje.mantenimiento.error.mantenimiento_no_valido' => 'Manteniment no vàlid',
    'garaje.mantenimiento.error.mantenimiento_no_encontrado' => 'Manteniment no trobat o sense permisos',
    'garaje.mantenimiento.error.actualizar' => 'No s’ha pogut actualitzar el manteniment',
    'garaje.mantenimiento.ok.actualizar' => 'Manteniment actualitzat correctament',
    'garaje.mantenimiento.error.eliminar' => 'No s’ha pogut eliminar el manteniment',
    'garaje.mantenimiento.ok.eliminar' => 'Manteniment eliminat correctament',

    // comunitat - llistat
    'comunidad.index.titulo_pagina' => 'Comunitat',
    'comunidad.index.titulo' => 'Comunitat',
    'comunidad.index.crear_publicacion' => '+ Crear publicació',
    'comunidad.index.buscar_publicaciones' => 'Cercar publicacions',
    'comunidad.index.placeholder_busqueda' => 'Contingut o autor',
    'comunidad.index.ordenar_por' => 'Ordenar per',
    'comunidad.index.orden.recientes' => 'Més recents',
    'comunidad.index.orden.antiguas' => 'Més antigues',
    'comunidad.index.orden.likes' => 'Més m’agrada',
    'comunidad.index.orden.comentarios' => 'Més comentaris',
    'comunidad.index.aplicar_filtros' => 'Aplicar filtres',
    'comunidad.index.limpiar' => 'Netejar',
    'comunidad.index.sin_publicaciones' => 'No s’han trobat publicacions',
    'comunidad.index.por' => 'per',
    'comunidad.index.alt_imagen_publicacion' => 'Imatge de la publicació',
    'comunidad.index.comentario_singular' => 'comentari',
    'comunidad.index.comentario_plural' => 'comentaris',
    'comunidad.index.like_singular' => 'm’agrada',
    'comunidad.index.like_plural' => 'm’agrada',
    'comunidad.index.dar_like' => 'Donar m’agrada',
    'comunidad.index.quitar_like' => 'Treure m’agrada',
    'comunidad.index.ver_publicacion' => 'Veure publicació',
    'comunidad.index.editar_publicacion' => 'Editar publicació',
    'comunidad.index.eliminar_publicacion' => 'Eliminar publicació',
    'comunidad.index.confirmar_eliminar_publicacion' => 'Segur que vols eliminar aquesta publicació?',
    'comunidad.index.publicacion_encontrada' => 'publicació trobada',
    'comunidad.index.publicaciones_encontradas' => 'publicacions trobades',
    'comunidad.index.paginacion_aria' => 'Paginació de publicacions',
    'comunidad.index.pagina_de' => 'Pàgina {actual} de {total}',
    'comunidad.index.anterior' => 'Anterior',
    'comunidad.index.siguiente' => 'Següent',

    // comunitat - detall
    'comunidad.detalle.titulo_pagina' => 'Detall de publicació',
    'comunidad.detalle.titulo' => 'Detall de publicació',
    'comunidad.detalle.error.cargar' => 'No s’ha pogut carregar la publicació',
    'comunidad.detalle.anadir_comentario' => 'Afegir comentari',
    'comunidad.detalle.comentario' => 'Comentari',
    'comunidad.detalle.publicar_comentario' => 'Publicar comentari',
    'comunidad.detalle.comentarios' => 'Comentaris',
    'comunidad.detalle.sin_comentarios' => 'Encara no hi ha comentaris en aquesta publicació',
    'comunidad.detalle.editar_comentario' => 'Editar comentari',
    'comunidad.detalle.eliminar_comentario' => 'Eliminar comentari',
    'comunidad.detalle.confirmar_eliminar_comentario' => 'Segur que vols eliminar aquest comentari?',
    'comunidad.detalle.responder' => 'Respondre',
    'comunidad.detalle.tu_respuesta' => 'La teva resposta',
    'comunidad.detalle.publicar_respuesta' => 'Publicar resposta',
    'comunidad.detalle.ver_una_respuesta' => 'Veure 1 resposta',
    'comunidad.detalle.ver_respuestas' => 'Veure {total} respostes',
    'comunidad.detalle.ocultar_respuestas' => 'Amagar respostes',
    'comunidad.detalle.cargando_respuestas' => 'Carregant respostes...',
    'comunidad.detalle.error_cargar_respuestas' => 'No s’han pogut carregar les respostes',
    'comunidad.detalle.sin_respuestas' => 'No hi ha respostes',
    'comunidad.detalle.volver' => 'Tornar a comunitat',

    // comunitat - formularis
    'comunidad.form.nueva.titulo_pagina' => 'Crear publicació',
    'comunidad.form.nueva.titulo' => 'Crear publicació',
    'comunidad.form.contenido' => 'Contingut',
    'comunidad.form.imagen_opcional' => 'Imatge opcional',
    'comunidad.form.publicar' => 'Publicar',
    'comunidad.form.volver_comunidad' => 'Tornar a comunitat',

    'comunidad.form.editar.titulo_pagina' => 'Editar publicació',
    'comunidad.form.editar.titulo' => 'Editar publicació',
    'comunidad.form.editar.error_cargar' => 'No s’ha pogut carregar la publicació',
    'comunidad.form.imagen_actual' => 'Imatge actual',
    'comunidad.form.alt_imagen_actual' => 'Imatge actual de la publicació',
    'comunidad.form.nueva_imagen_opcional' => 'Nova imatge opcional',
    'comunidad.form.guardar_cambios' => 'Guardar canvis',
    'comunidad.form.volver_publicacion' => 'Tornar a la publicació',

    'comunidad.form.editar_comentario.titulo_pagina' => 'Editar comentari',
    'comunidad.form.editar_comentario.titulo' => 'Editar comentari',
    'comunidad.form.editar_comentario.error_cargar' => 'No s’ha pogut carregar el comentari',
    'comunidad.form.editar_comentario.comentario' => 'Comentari',

    // comunitat - missatges backend/ajax
    'comunidad.error.contenido_obligatorio' => 'El contingut és obligatori',
    'comunidad.error.imagen_formato' => 'Format d’imatge no permès',
    'comunidad.error.guardar_publicacion' => 'No s’ha pogut guardar la publicació',
    'comunidad.ok.publicacion_creada' => 'Publicació creada correctament',
    'comunidad.error.publicacion_no_valida' => 'Publicació no vàlida',
    'comunidad.error.publicacion_no_existe' => 'La publicació no existeix',
    'comunidad.error.datos_respuesta_no_validos' => 'Dades de resposta no vàlides',
    'comunidad.error.comentario_responder_no_valido' => 'El comentari al qual intentes respondre no és vàlid',
    'comunidad.error.respuesta_vacia' => 'La resposta no pot estar buida',
    'comunidad.error.guardar_respuesta' => 'No s’ha pogut guardar la resposta',
    'comunidad.ok.respuesta_publicada' => 'Resposta publicada correctament',
    'comunidad.error.comentario_vacio' => 'El comentari no pot estar buit',
    'comunidad.error.guardar_comentario' => 'No s’ha pogut guardar el comentari',
    'comunidad.ok.comentario_publicado' => 'Comentari publicat correctament',
    'comunidad.error.like_actualizar' => 'No s’ha pogut actualitzar el m’agrada',
    'comunidad.error.sin_permiso_editar_publicacion' => 'No tens permís per editar aquesta publicació',
    'comunidad.error.sin_permiso_eliminar_publicacion' => 'No tens permís per eliminar aquesta publicació',
    'comunidad.error.eliminar_publicacion' => 'No s’ha pogut eliminar la publicació',
    'comunidad.ok.publicacion_eliminada' => 'Publicació eliminada correctament',
    'comunidad.error.datos_no_validos' => 'Dades no vàlides',
    'comunidad.error.comentario_no_valido' => 'El comentari no és vàlid',

    'comunidad.error.subir_imagen' => 'No se pudo subir la imagen',
    'comunidad.error.actualizar_publicacion' => 'No se pudo actualizar la publicación',
    'comunidad.ok.publicacion_actualizada' => 'Publicación actualizada correctamente',

    'comunidad.error.comentario_no_existe' => 'El comentario no existe',
    'comunidad.error.sin_permiso_editar_comentario' => 'No tienes permiso para editar este comentario',
    'comunidad.error.comentario_contenido_obligatorio' => 'El contenido del comentario es obligatorio',
    'comunidad.error.actualizar_comentario' => 'No se pudo actualizar el comentario',
    'comunidad.ok.comentario_actualizado' => 'Comentario actualizado correctamente',
    'comunidad.error.sin_permiso_eliminar_comentario' => 'No tienes permiso para eliminar este comentario',
    'comunidad.error.eliminar_comentario' => 'No se pudo eliminar el comentario',
    'comunidad.ok.comentario_eliminado' => 'Comentario eliminado correctamente',

    // perfil
    'perfil.error.cargar' => 'No s’ha pogut carregar el perfil',
    'perfil.error.no_valido' => 'Perfil no vàlid',
    'perfil.error.no_existe' => 'El perfil no existeix',
    'perfil.error.usuario_no_encontrado' => 'Usuari no trobat',
    'perfil.error.imagen_obligatoria' => 'Has de seleccionar una imatge',
    'perfil.error.subir_foto' => 'No s’ha pogut pujar la foto de perfil',
    'perfil.error.archivo_no_valido' => 'El fitxer pujat no és vàlid',
    'perfil.error.imagen_tamanyo' => 'La imatge no pot superar els 3 MB',
    'perfil.error.imagen_formato' => 'Només es permeten imatges JPG, PNG o WEBP',
    'perfil.error.crear_directorio' => 'No s’ha pogut crear el directori de fotos de perfil',
    'perfil.error.guardar_foto' => 'No s’ha pogut guardar la foto de perfil',
    'perfil.ok.foto_actualizada' => 'Foto de perfil actualitzada',
    'perfil.error.campos_obligatorios' => 'Tots els camps són obligatoris',
    'perfil.error.nombre_reglas' => 'El nom d’usuari no compleix les regles permeses',
    'perfil.error.email_no_valido' => 'El correu electrònic no és vàlid',
    'perfil.error.nombre_en_uso' => 'El nom d’usuari ja està en ús',
    'perfil.error.email_en_uso' => 'El correu electrònic ja està en ús',
    'perfil.ok.actualizado' => 'Perfil actualitzat correctament',
    'perfil.error.password_obligatoria' => 'Tots els camps de contrasenya són obligatoris',
    'perfil.error.password_actual' => 'La contrasenya actual no és correcta',
    'perfil.error.password_no_coincide' => 'Les noves contrasenyes no coincideixen',
    'perfil.error.password_requisitos' => 'La nova contrasenya ha de tenir mínim 8 caràcters, una majúscula, una minúscula i un número',
    'perfil.error.password_igual' => 'La nova contrasenya no pot ser igual que l’actual',
    'perfil.ok.password_actualizada' => 'Contrasenya actualitzada correctament',

    'perfil.ver.titulo_pagina' => 'Perfil',
    'perfil.ver.titulo_de' => 'Perfil de',
    'perfil.ver.alt_foto' => 'Foto de perfil de',
    'perfil.ver.sin_foto' => 'Sense foto',
    'perfil.ver.cambiar_foto' => 'Canviar foto de perfil',
    'perfil.ver.nueva_foto' => 'Nova foto',
    'perfil.ver.actualizar_foto' => 'Actualitzar foto',
    'perfil.ver.editar_datos' => 'Editar dades del perfil',
    'perfil.ver.nombre_usuario' => 'Nom d’usuari',
    'perfil.ver.email' => 'Correu electrònic',
    'perfil.ver.guardar_cambios' => 'Guardar canvis',
    'perfil.ver.cambiar_password' => 'Canviar contrasenya',
    'perfil.ver.password_actual' => 'Contrasenya actual',
    'perfil.ver.password_nueva' => 'Nova contrasenya',
    'perfil.ver.password_nueva_repetida' => 'Repetir nova contrasenya',
    'perfil.ver.garaje_publico' => 'Garatge públic',
    'perfil.ver.sin_vehiculos' => 'Aquest usuari encara no té vehicles al seu garatge',
    'perfil.ver.sin_imagen' => 'Sense imatge',
    'perfil.ver.alt_vehiculo' => 'Imatge de',
    'perfil.ver.ver_detalles' => 'Veure detalls',
    'perfil.ver.publicaciones' => 'Publicacions',
    'perfil.ver.sin_publicaciones' => 'Aquest usuari encara no té publicacions',
    'perfil.ver.alt_publicacion' => 'Imatge de la publicació',
    'perfil.ver.comentario_singular' => 'comentari',
    'perfil.ver.comentario_plural' => 'comentaris',
    'perfil.ver.like_singular' => 'm’agrada',
    'perfil.ver.like_plural' => 'm’agrada',
    'perfil.ver.ver_publicacion' => 'Veure publicació',
    'perfil.ver.opciones_perfil' => 'Opcions del perfil',
    'perfil.ver.boton_publicaciones' => 'Publicacions',
    'perfil.ver.boton_configuracion' => 'Configuració',
    'perfil.ver.boton_atras' => 'Enrere',

    // perfil - vehicle públic
    'perfil.vehiculo.error.cargar' => 'No s’ha pogut carregar el vehicle',
    'perfil.vehiculo.error.no_valido' => 'Vehicle no vàlid',
    'perfil.vehiculo.error.no_existe' => 'El vehicle no existeix',
    'perfil.vehiculo.titulo_pagina' => 'Vehicle públic',
    'perfil.vehiculo.propietario' => 'Propietari',
    'perfil.vehiculo.alt_imagen' => 'Imatge del vehicle',
    'perfil.vehiculo.detalles_publicos' => 'Detalls públics',
    'perfil.vehiculo.any' => 'Any',
    'perfil.vehiculo.carroceria' => 'Carrosseria',
    'perfil.vehiculo.combustible' => 'Combustible',
    'perfil.vehiculo.cambio' => 'Canvi',
    'perfil.vehiculo.potencia' => 'Potència',
    'perfil.vehiculo.cilindrada' => 'Cilindrada',
    'perfil.vehiculo.volver_perfil' => 'Tornar al perfil',

    // diagnòstic ia
    'diagnostico.titulo_pagina' => 'Diagnòstic assistit',
    'diagnostico.titulo' => 'Diagnòstic assistit',
    'diagnostico.descripcion' => 'Descriu els símptomes del vehicle i TorqHub analitzarà possibles causes mitjançant un sistema expert basat en regles.',
    'diagnostico.reiniciar' => '↺ Reiniciar xat',
    'diagnostico.ia_nombre' => 'TorqHub IA',
    'diagnostico.usuario' => 'Tu',
    'diagnostico.mensaje_inicial' => 'Hola, digues-me què li passa al teu cotxe. Per exemple: “el cotxe no arrenca i fa clic”.',
    'diagnostico.resultados_intro' => 'He trobat aquestes possibles causes:',
    'diagnostico.confianza_aproximada' => 'Confiança aproximada',
    'diagnostico.coincidencias_detectadas' => 'Coincidències detectades',
    'diagnostico.recomendacion' => 'Recomanació',
    'diagnostico.sin_resultados' => 'No he trobat una causa clara. Prova descrivint símptomes més concrets com soroll, temperatura, arrencada, frens, direcció o pèrdua de potència.',
    'diagnostico.label_sintomas' => 'Símptomes del vehicle',
    'diagnostico.placeholder_sintomas' => 'Escriu aquí els símptomes...',
    'diagnostico.boton_analizar' => 'Analitzar',
    'diagnostico.estado_analizando' => 'Analitzant...',
    'diagnostico.error.sintomas_obligatorios' => 'Has d’escriure els símptomes del vehicle',
    'diagnostico.error.analisis' => 'S’ha produït un error en analitzar els símptomes',
    'diagnostico.error.conexion' => 'No s’ha pogut connectar amb el sistema de diagnòstic',

    // diagnòstic ia - causes
    'diagnostico.causa.bateria.titulo' => 'Bateria descarregada o en mal estat',
    'diagnostico.causa.bateria.recomendacion' => 'Revisar la càrrega de la bateria, borns i alternador abans de substituir-la.',
    'diagnostico.causa.arranque.titulo' => 'Fallada en el motor d’arrencada',
    'diagnostico.causa.arranque.recomendacion' => 'Comprovar el motor d’arrencada, el relé i les connexions elèctriques.',
    'diagnostico.causa.encendido.titulo' => 'Problema de bugies o encesa',
    'diagnostico.causa.encendido.recomendacion' => 'Revisar bugies, bobines i sistema d’encesa.',
    'diagnostico.causa.filtros.titulo' => 'Filtre d’aire o combustible obstruït',
    'diagnostico.causa.filtros.recomendacion' => 'Revisar els filtres i substituir-los si estan bruts.',
    'diagnostico.causa.sobrecalentamiento.titulo' => 'Sobreescalfament del motor',
    'diagnostico.causa.sobrecalentamiento.recomendacion' => 'Aturar el vehicle i revisar refrigerant, radiador, termòstat i ventilador.',
    'diagnostico.causa.frenos.titulo' => 'Fallada en els frens',
    'diagnostico.causa.frenos.recomendacion' => 'Revisar pastilles, discos, líquid de frens i possibles fuites.',
    'diagnostico.causa.embrague.titulo' => 'Problema d’embragatge',
    'diagnostico.causa.embrague.recomendacion' => 'Revisar el desgast de l’embragatge i el sistema hidràulic.',
    'diagnostico.causa.neumaticos.titulo' => 'Pneumàtics o alineació incorrecta',
    'diagnostico.causa.neumaticos.recomendacion' => 'Comprovar pressió, equilibratge, alineació i estat dels pneumàtics.',

    // garatge - eliminar vehicle
    'garaje.eliminar.titulo_pagina' => 'Eliminar vehicle',
    'garaje.eliminar.titulo' => 'Eliminar vehicle',
    'garaje.eliminar.error.cargar' => 'No s’ha pogut carregar el vehicle per eliminar',
    'garaje.eliminar.confirmacion' => 'Segur que vols eliminar aquest vehicle?',
    'garaje.eliminar.cancelar' => 'Cancel·lar',
    'garaje.eliminar.eliminar' => 'Eliminar',

    // admin
    'admin.titulo_pagina' => 'Panell d’administració',
    'admin.titulo' => 'Panell d’administració',
    'admin.descripcion' => 'Zona privada per gestionar les parts principals de TorqHub des d’un únic panell.',
    'admin.secciones' => 'Seccions del panell d’administració',

    'admin.tarjeta.usuarios.etiqueta' => 'Usuaris',
    'admin.tarjeta.usuarios.titulo' => 'Gestió d’usuaris',
    'admin.tarjeta.usuarios.descripcion' => 'Consultar usuaris registrats, revisar rols i preparar accions d’administració.',

    'admin.tarjeta.publicaciones.etiqueta' => 'Comunitat',
    'admin.tarjeta.publicaciones.titulo' => 'Gestió de publicacions',
    'admin.tarjeta.publicaciones.descripcion' => 'Revisar contingut publicat per la comunitat i moderar publicacions si cal.',

    'admin.tarjeta.ia.etiqueta' => 'Diagnòstic',
    'admin.tarjeta.ia.titulo' => 'Base de coneixement IA',
    'admin.tarjeta.ia.descripcion' => 'Consultar l’estat del sistema expert i preparar-ne la futura gestió des de base de dades.',

    'admin.usuarios.titulo_pagina' => 'Gestió d’usuaris',
    'admin.usuarios.titulo' => 'Gestió d’usuaris',
    'admin.usuarios.descripcion' => 'Des d’aquí pots revisar usuaris registrats, canviar rols i activar o desactivar comptes sense eliminar dades relacionades.',
    'admin.usuarios.volver' => 'Tornar al panell d’administració',
    'admin.usuarios.sin_usuarios' => 'No hi ha usuaris registrats',

    'admin.usuarios.id' => 'ID',
    'admin.usuarios.nombre' => 'Nom',
    'admin.usuarios.email' => 'Correu electrònic',
    'admin.usuarios.rol' => 'Rol',
    'admin.usuarios.estado' => 'Estat',
    'admin.usuarios.fecha_creacion' => 'Data de creació',
    'admin.usuarios.acciones' => 'Accions',

    'admin.usuarios.rol.usuario' => 'Usuari',
    'admin.usuarios.rol.admin' => 'Administrador',
    'admin.usuarios.activo' => 'Actiu',
    'admin.usuarios.inactivo' => 'Inactiu',
    'admin.usuarios.cambiar_rol' => 'Canviar rol',
    'admin.usuarios.guardar_rol' => 'Desar rol',
    'admin.usuarios.activar' => 'Activar',
    'admin.usuarios.desactivar' => 'Desactivar',
    'admin.usuarios.accion_propia' => 'No pots modificar el teu propi compte des d’aquí',

    'admin.usuarios.ok.rol_actualizado' => 'Rol actualitzat correctament',
    'admin.usuarios.ok.usuario_activado' => 'Usuari activat correctament',
    'admin.usuarios.ok.usuario_desactivado' => 'Usuari desactivat correctament',

    'admin.usuarios.error.listar' => 'No s’han pogut carregar els usuaris',
    'admin.usuarios.error.datos_invalidos' => 'Les dades enviades no són vàlides',
    'admin.usuarios.error.rol_invalido' => 'El rol seleccionat no és vàlid',
    'admin.usuarios.error.autorol' => 'No pots treure’t a tu mateix el rol d’administrador',
    'admin.usuarios.error.autodesactivar' => 'No pots desactivar el teu propi compte',
    'admin.usuarios.error.actualizar_rol' => 'No s’ha pogut actualitzar el rol',
    'admin.usuarios.error.actualizar_estado' => 'No s’ha pogut actualitzar l’estat de l’usuari',

    'admin.publicaciones.titulo_pagina' => 'Gestió de publicacions',
    'admin.publicaciones.titulo' => 'Gestió de publicacions',
    'admin.publicaciones.descripcion' => 'Des d’aquí pots revisar publicacions de la comunitat i eliminar contingut si incompleix les normes.',
    'admin.publicaciones.volver' => 'Tornar al panell d’administració',
    'admin.publicaciones.sin_publicaciones' => 'No hi ha publicacions registrades',

    'admin.publicaciones.id' => 'ID',
    'admin.publicaciones.autor' => 'Autor',
    'admin.publicaciones.contenido' => 'Contingut',
    'admin.publicaciones.imagen' => 'Imatge',
    'admin.publicaciones.estadisticas' => 'Estadístiques',
    'admin.publicaciones.fecha' => 'Data',
    'admin.publicaciones.acciones' => 'Accions',

    'admin.publicaciones.comentarios' => 'comentaris',
    'admin.publicaciones.likes' => 'likes',
    'admin.publicaciones.ver' => 'Veure publicació',
    'admin.publicaciones.eliminar' => 'Eliminar publicació',
    'admin.publicaciones.confirmar_eliminar' => 'Confirmar eliminació',
    'admin.publicaciones.alt_imagen' => 'Imatge de la publicació',

    'admin.publicaciones.ok.eliminada' => 'Publicació eliminada correctament',

    'admin.publicaciones.error.listar' => 'No s’han pogut carregar les publicacions',
    'admin.publicaciones.error.datos_invalidos' => 'Les dades enviades no són vàlides',
    'admin.publicaciones.error.confirmacion' => 'Has de confirmar l’eliminació',
    'admin.publicaciones.error.no_existe' => 'La publicació no existeix',
    'admin.publicaciones.error.eliminar' => 'No s’ha pogut eliminar la publicació',

    'admin.ia.titulo_pagina' => 'Base de coneixement IA',
    'admin.ia.titulo' => 'Base de coneixement IA',
    'admin.ia.descripcion' => 'Gestió bàsica de la base de coneixement del sistema de diagnòstic assistit de TorqHub.',
    'admin.ia.volver' => 'Tornar al panell d’administració',

    'admin.ia.resumen.titulo' => 'Resum de la base de coneixement',
    'admin.ia.resumen.texto' => 'El sistema expert carrega causes mecàniques i paraules clau des de base de dades. Si la càrrega falla, el motor manté un fallback intern per no trencar el xat de diagnòstic.',
    'admin.ia.resumen.causas' => 'causes registrades',
    'admin.ia.resumen.keywords' => 'keywords registrades',

    'admin.ia.sin_causas' => 'No hi ha causes registrades a la base de coneixement',
    'admin.ia.sin_keywords' => 'Sense keywords',

    'admin.ia.tabla.id' => 'ID',
    'admin.ia.tabla.causa' => 'Causa',
    'admin.ia.tabla.recomendacion' => 'Recomanació',
    'admin.ia.tabla.estado' => 'Estat',
    'admin.ia.tabla.keywords' => 'Keywords',
    'admin.ia.tabla.fecha' => 'Data de creació',

    'admin.ia.estado.activa' => 'Activa',
    'admin.ia.estado.inactiva' => 'Inactiva',

    'admin.ia.defensa.titulo' => 'Defensa tècnica',
    'admin.ia.defensa.texto' => 'Aquesta migració converteix el diagnòstic en una base de coneixement persistent sense canviar l’experiència de l’usuari ni dependre de serveis externs.',
    'admin.ia.defensa.aviso' => 'Decisió defensable: el sistema continua sent propi, gratuït, privat i mantenible des de base de dades.',

    'admin.ia.error.listar' => 'No s’ha pogut carregar la base de coneixement IA',

    'admin.ia.tabla.acciones' => 'Accions',

    'admin.ia.activar' => 'Activar',
    'admin.ia.desactivar' => 'Desactivar',

    'admin.ia.ok.causa_activada' => 'Causa IA activada correctament',
    'admin.ia.ok.causa_desactivada' => 'Causa IA desactivada correctament',

    'admin.ia.error.datos_invalidos' => 'Les dades enviades no són vàlides',
    'admin.ia.error.no_existe' => 'La causa IA indicada no existeix',
    'admin.ia.error.actualizar_estado' => 'No s’ha pogut actualitzar l’estat de la causa IA',

    // garatge - missatges de vehicle
    'garaje.vehiculo.error.carroceria_no_valida' => 'La carrosseria no és vàlida',
    'garaje.vehiculo.error.combustible_no_valido' => 'El tipus de combustible no és vàlid',
    'garaje.vehiculo.error.cambio_no_valido' => 'El tipus de canvi no és vàlid',
    'garaje.vehiculo.error.potencia_entero' => 'La potència en CV ha de ser un número enter positiu',
    'garaje.vehiculo.error.cilindrada_entero' => 'La cilindrada ha de ser un número enter positiu',
    'garaje.vehiculo.error.marca_modelo_any_obligatorios' => 'Marca, model i any són obligatoris',
    'garaje.vehiculo.error.marca_modelo_obligatorios' => 'Marca i model són obligatoris',
    'garaje.vehiculo.error.no_valido' => 'Vehicle no vàlid',
    'garaje.vehiculo.error.no_encontrado' => 'Vehicle no trobat',
    'garaje.vehiculo.error.no_encontrado_permisos' => 'Vehicle no trobat o sense permisos',
    'garaje.vehiculo.error.guardar' => 'No s’ha pogut guardar el vehicle',
    'garaje.vehiculo.error.actualizar' => 'No s’ha pogut actualitzar el vehicle',
    'garaje.vehiculo.error.eliminar' => 'No s’ha pogut eliminar el vehicle',
    'garaje.vehiculo.ok.creado' => 'Vehicle afegit correctament',
    'garaje.vehiculo.ok.actualizado' => 'Vehicle actualitzat correctament',
    'garaje.vehiculo.ok.eliminado' => 'Vehicle eliminat correctament',

    // garatge - imatge de vehicle
    'garaje.vehiculo.imagen.error.subir' => 'No s’ha pogut pujar la imatge del vehicle',
    'garaje.vehiculo.imagen.error.archivo_no_valido' => 'El fitxer pujat no és vàlid',
    'garaje.vehiculo.imagen.error.tamanyo' => 'La imatge no pot superar els 3 MB',
    'garaje.vehiculo.imagen.error.formato' => 'Només es permeten imatges JPG, PNG o WEBP',
    'garaje.vehiculo.imagen.error.crear_directorio' => 'No s’ha pogut crear el directori d’imatges de vehicles',
    'garaje.vehiculo.imagen.error.guardar' => 'No s’ha pogut guardar la imatge del vehicle',
    'garaje.vehiculo.imagen.error.limite' => 'Pots pujar un màxim de 8 fotos alhora',

    // garatge - vin backend
    'garaje.vin.error.obligatorio' => 'Has d’introduir un VIN',
    'garaje.vin.ok.cache' => 'VIN trobat a la memòria cau',
    'garaje.vin.ok.api' => 'VIN consultat a l’API externa',
    'garaje.vin.error.cache' => 'No s’ha pogut guardar la memòria cau del VIN',

    // garatge - filtres backend
    'garaje.filtros.error.fecha_desde_no_valida' => 'La data des de no és vàlida',
    'garaje.filtros.error.fecha_hasta_no_valida' => 'La data fins no és vàlida',
    'garaje.filtros.error.fecha_desde_mayor' => 'La data des de no pot ser més gran que la data fins',
    'garaje.filtros.error.km_minimos' => 'Els quilòmetres mínims han de ser un número enter positiu',
    'garaje.filtros.error.km_maximos' => 'Els quilòmetres màxims han de ser un número enter positiu',
    'garaje.filtros.error.km_minimos_mayores' => 'Els quilòmetres mínims no poden ser més grans que els màxims',
    'garaje.filtros.error.coste_minimo' => 'El cost mínim no és vàlid',
    'garaje.filtros.error.coste_maximo' => 'El cost màxim no és vàlid',
    'garaje.filtros.error.coste_minimo_mayor' => 'El cost mínim no pot ser més gran que el cost màxim',
    'garaje.filtros.error.orden_campo' => 'El camp d’ordenació no és vàlid',
    'garaje.filtros.error.orden_direccion' => 'La direcció d’ordenació no és vàlida',

    // garatge - opcions de selects
    'garaje.opcion.carroceria.coche_pequeno' => 'Cotxe petit',
    'garaje.opcion.carroceria.sedan' => 'Sedan',
    'garaje.opcion.carroceria.familiar' => 'Familiar',
    'garaje.opcion.carroceria.cabrio' => 'Cabrio',
    'garaje.opcion.carroceria.coupe' => 'Cupè',
    'garaje.opcion.carroceria.suv_4x4' => 'SUV/4x4',
    'garaje.opcion.carroceria.monovolumen' => 'Monovolum',
    'garaje.opcion.carroceria.furgoneta' => 'Furgoneta',
    'garaje.opcion.carroceria.otros' => 'Altres',

    'garaje.opcion.combustible.gasolina' => 'Gasolina',
    'garaje.opcion.combustible.diesel' => 'Dièsel',
    'garaje.opcion.combustible.electrico' => 'Elèctric',
    'garaje.opcion.combustible.electro_gasolina' => 'Elèctric/gasolina',
    'garaje.opcion.combustible.electro_diesel' => 'Elèctric/dièsel',
    'garaje.opcion.combustible.gas_natural' => 'Gas natural (CNG)',
    'garaje.opcion.combustible.etanol' => 'Etanol',
    'garaje.opcion.combustible.hidrogeno' => 'Hidrogen',
    'garaje.opcion.combustible.glp' => 'Gas liquat (GLP)',
    'garaje.opcion.combustible.otros' => 'Altres',

    'garaje.opcion.cambio.automatico' => 'Automàtic',
    'garaje.opcion.cambio.manual' => 'Manual',

    // middlewares
    'middleware.auth.error.login_requerido' => 'Has d’iniciar sessió per accedir a aquesta pàgina',
    'middleware.admin.error.login_requerido' => 'Has d’iniciar sessió',
    'middleware.admin.error.acceso_denegado' => '403 - Accés denegat',

    // servei vin
    'garaje.vin.error.formato' => 'El VIN ha de tenir 17 caràcters i no pot contenir I, O ni Q',
    'garaje.vin.error.curl_no_disponible' => 'cURL no està disponible a PHP',
    'garaje.vin.error.consulta_api' => 'No s’ha pogut consultar l’API VIN',
    'garaje.vin.error.codigo_http' => 'L’API VIN ha respost amb el codi HTTP {codigo}',
    'garaje.vin.error.json_no_valido' => 'La resposta de l’API VIN no és un JSON vàlid',
    'garaje.vin.error.sin_resultados' => 'L’API VIN no ha retornat resultats vàlids',
];
