<?php

return [
    // nav
    'navbar.inicio' => 'Inicio',
    'navbar.login' => 'Iniciar sesión',
    'navbar.registro' => 'Registrarse',
    'navbar.garaje' => 'Mi garaje',
    'navbar.comunidad' => 'Comunidad',
    'navbar.diagnostico' => 'Diagnóstico',
    'navbar.perfil' => 'Mi perfil',
    'navbar.admin' => 'Panel de administración',
    'navbar.logout' => 'Cerrar sesión',

    'navbar.idioma_es' => 'ES',
    'navbar.idioma_ca' => 'CA',
    'navbar.cambiar_idioma' => 'Cambiar idioma',

    'idioma.ok.cambiado' => 'Idioma actualizado correctamente',

    // seguridad
    'seguridad.error.csrf' => 'La sesión de seguridad ha caducado. Recarga la página e inténtalo de nuevo',
    'seguridad.error.servidor' => 'Se ha producido un error interno. Inténtalo de nuevo más tarde',
    'seguridad.error.ruta_no_encontrada' => 'Página no encontrada',

    // auth - login
    'auth.login.titulo_pagina' => 'Iniciar sesión',
    'auth.login.titulo' => 'Iniciar sesión',
    'auth.login.email' => 'Correo electrónico',
    'auth.login.password' => 'Contraseña',
    'auth.login.boton' => 'Entrar',
    'auth.login.password_olvidada' => 'He olvidado la contraseña',

    // auth - registro
    'auth.registro.titulo_pagina' => 'Registrarse',
    'auth.registro.titulo' => 'Registrarse',
    'auth.registro.nombre' => 'Nombre de usuario',
    'auth.registro.nombre_ayuda' => 'Solo letras minúsculas, números, puntos y guiones bajos, sin espacios, sin puntos consecutivos y sin terminar en punto',
    'auth.registro.email' => 'Correo electrónico',
    'auth.registro.password' => 'Contraseña',
    'auth.registro.password_repetida' => 'Repetir contraseña',
    'auth.registro.password_ayuda' => 'Mínimo 8 caracteres, una mayúscula, una minúscula y un número',
    'auth.registro.error_password_repetida' => 'Las contraseñas no coinciden',
    'auth.registro.boton' => 'Crear cuenta',

    // auth - recuperación
    'auth.password_olvidada.titulo_pagina' => 'Recuperar contraseña',
    'auth.password_olvidada.titulo' => 'Recuperar contraseña',
    'auth.password_olvidada.email' => 'Correo electrónico',
    'auth.password_olvidada.boton' => 'Enviar enlace de recuperación',
    'auth.password_olvidada.volver_login' => 'Volver a iniciar sesión',

    // auth - restablecer contraseña
    'auth.password_restablecer.titulo_pagina' => 'Restablecer contraseña',
    'auth.password_restablecer.titulo' => 'Restablecer contraseña',
    'auth.password_restablecer.password' => 'Nueva contraseña',
    'auth.password_restablecer.password_repetida' => 'Repetir contraseña',
    'auth.password_restablecer.boton' => 'Guardar nueva contraseña',

    // auth - mensajes
    'auth.error.rellena_login' => 'Rellena correo electrónico y contraseña',
    'auth.error.servidor' => 'Error de servidor, inténtalo más tarde',
    'auth.error.credenciales' => 'Credenciales incorrectas',
    'auth.ok.sesion_iniciada' => 'Sesión iniciada',
    'auth.ok.sesion_cerrada' => 'Sesión cerrada correctamente',

    'auth.error.registro_obligatorios' => 'Debes rellenar nombre de usuario, correo electrónico y contraseña',
    'auth.error.password_no_coincide' => 'Las contraseñas no coinciden',
    'auth.error.nombre_requisitos' => 'El nombre de usuario solo puede contener letras minúsculas, números, puntos y guiones bajos, sin espacios, sin puntos consecutivos y sin terminar en punto',
    'auth.error.password_requisitos' => 'La contraseña debe tener mínimo 8 caracteres, una mayúscula, una minúscula y un número',
    'auth.error.nombre_uso' => 'Ese nombre de usuario ya está en uso',
    'auth.error.email_registrado' => 'Ese correo electrónico ya está registrado',
    'auth.ok.registro_completado' => 'Registro completado, ahora inicia sesión',
    'auth.error.nombre_email_uso' => 'El nombre de usuario o el correo electrónico ya están en uso',
    'auth.error.registro_error' => 'Se produjo un error al registrar la cuenta',

    'auth.error.email_no_valido' => 'El correo electrónico no es válido',
    'auth.ok.recuperacion_enviada' => 'Si el correo existe, recibirás un enlace para restablecer la contraseña',
    'auth.error.token_no_valido' => 'Token no válido',
    'auth.error.enlace_expirado' => 'El enlace ya no es válido o ha expirado',
    'auth.error.enlace_restablecer_no_valido' => 'El enlace para restablecer la contraseña no es válido',
    'auth.error.campos_obligatorios' => 'Todos los campos son obligatorios',
    'auth.error.password_minimos' => 'La contraseña no cumple los requisitos mínimos',
    'auth.ok.password_restablecida' => 'Contraseña restablecida correctamente',

    // inicio
    'inicio.titulo_pagina' => 'Inicio',
    'inicio.titulo' => 'Inicio',
    'inicio.saludo' => 'Hola',
    'inicio.bienvenida' => 'Bienvenido a TorqHub',

    // garaje - listado
    'garaje.index.titulo_pagina' => 'Mi garaje',
    'garaje.index.titulo' => 'Mi garaje',
    'garaje.index.anadir_vehiculo' => 'Añadir vehículo',
    'garaje.index.sin_vehiculos' => 'Todavía no tienes vehículos',
    'garaje.index.ver' => 'Ver',
    'garaje.index.editar' => 'Editar',
    'garaje.index.eliminar' => 'Eliminar',

    // garaje - formulario vehículo
    'garaje.form.nuevo.titulo_pagina' => 'Añadir vehículo',
    'garaje.form.nuevo.titulo' => 'Añadir vehículo',
    'garaje.form.editar.titulo_pagina' => 'Editar vehículo',
    'garaje.form.editar.titulo' => 'Editar vehículo',

    'garaje.form.error.cargar_editar' => 'No se ha podido cargar el vehículo para editar',

    'garaje.form.marca' => 'Marca',
    'garaje.form.modelo' => 'Modelo',
    'garaje.form.any' => 'Año',
    'garaje.form.vin_opcional' => 'VIN',
    'garaje.form.vin' => 'VIN',
    'garaje.form.consultar_vin' => 'Consultar VIN',
    'garaje.form.vin_ayuda_nuevo' => 'Introduce un VIN real de 17 caracteres para autocompletar datos del vehículo',
    'garaje.form.vin_ayuda_editar' => 'Si consultas el VIN, se intentarán autocompletar los datos disponibles',

    'garaje.form.carroceria' => 'Carrocería',
    'garaje.form.tipo_combustible' => 'Tipo de combustible',
    'garaje.form.tipo_cambio' => 'Tipo de cambio',
    'garaje.form.selecciona_opcion' => 'Selecciona una opción',

    'garaje.form.potencia_cv' => 'Potencia (CV)',
    'garaje.form.cilindrada_cm3' => 'Cilindrada (cm³)',

    'garaje.form.imagen' => 'Imagen del vehículo',
    'garaje.form.imagen_ayuda_nuevo' => 'Formatos permitidos: JPG, PNG o WEBP. Máximo 3 MB',
    'garaje.form.cambiar_imagen' => 'Cambiar imagen del vehículo',
    'garaje.form.cambiar_imagen_ayuda' => 'Si subes una nueva imagen, reemplazará la actual. Máximo 3 MB',
    'garaje.form.imagen_actual' => 'Imagen actual',
    'garaje.form.alt_imagen_actual' => 'Imagen actual del vehículo',

    'garaje.form.cancelar' => 'Cancelar',
    'garaje.form.guardar_vehiculo' => 'Guardar vehículo',
    'garaje.form.guardar_cambios' => 'Guardar cambios',

    // garaje - mensajes javascript
    'garaje.js.campo.marca' => 'la marca',
    'garaje.js.campo.modelo' => 'el modelo',
    'garaje.js.campo.any' => 'el año',
    'garaje.js.campo.vin' => 'el VIN',
    'garaje.js.campo.carroceria' => 'la carrocería',
    'garaje.js.campo.tipo_combustible' => 'el tipo de combustible',
    'garaje.js.campo.tipo_cambio' => 'el tipo de cambio',
    'garaje.js.campo.potencia_cv' => 'la potencia',
    'garaje.js.campo.cilindrada_cm3' => 'la cilindrada',
    'garaje.js.campo.imagen' => 'la imagen',
    'garaje.js.campo.este_campo' => 'este campo',

    'garaje.js.error.falta' => 'Falta {campo}',
    'garaje.js.error.any_rango' => 'El año debe estar entre {minimo} y {maximo}',
    'garaje.js.error.potencia_entero' => 'La potencia debe ser un número entero positivo',
    'garaje.js.error.cilindrada_entero' => 'La cilindrada debe ser un número entero positivo',
    'garaje.js.error.imagen_tipo' => 'Solo se permiten imágenes JPG, PNG o WEBP',
    'garaje.js.error.imagen_tamanyo' => 'La imagen no puede superar los 3 MB',

    'garaje.js.vin.no_preparar' => 'No se pudo preparar la consulta VIN',
    'garaje.js.vin.introduce' => 'Introduce un VIN antes de consultar',
    'garaje.js.vin.formato' => 'El VIN debe tener 17 caracteres y no puede contener I, O ni Q',
    'garaje.js.vin.consultando_boton' => 'Consultando...',
    'garaje.js.vin.consultando_mensaje' => 'Consultando VIN...',
    'garaje.js.vin.respuesta_no_json' => 'La respuesta del servidor no es JSON válido',
    'garaje.js.vin.no_consultar' => 'No se pudo consultar el VIN',
    'garaje.js.vin.origen_cache' => 'caché local',
    'garaje.js.vin.origen_api' => 'API externa',
    'garaje.js.vin.ok_desde' => 'VIN consultado correctamente desde {origen}',

    // garaje - detalle vehículo
    'garaje.detalle.titulo_pagina' => 'Detalle del vehículo',
    'garaje.detalle.titulo' => 'Detalle del vehículo',
    'garaje.detalle.error.cargar' => 'No se ha podido cargar el vehículo',
    'garaje.detalle.alt_imagen' => 'Imagen del vehículo',
    'garaje.detalle.imagen_no_disponible' => 'Imagen no disponible',
    'garaje.detalle.imagen_ayuda' => 'Todavía no se ha subido una foto para este vehículo',
    'garaje.detalle.subtitulo' => 'Vehículo registrado en tu garaje',
    'garaje.detalle.volver_garaje' => 'Volver al garaje',
    'garaje.detalle.editar' => 'Editar',
    'garaje.detalle.eliminar' => 'Eliminar',
    'garaje.detalle.estadisticas' => 'Estadísticas rápidas',
    'garaje.detalle.total_gastado' => 'Total gastado',
    'garaje.detalle.mantenimientos' => 'Mantenimientos',
    'garaje.detalle.ultimo_mantenimiento' => 'Último mantenimiento',
    'garaje.detalle.sin_registros' => 'Sin registros',
    'garaje.detalle.no_indicado' => 'No indicado',
    'garaje.detalle.marca' => 'Marca',
    'garaje.detalle.modelo' => 'Modelo',
    'garaje.detalle.any' => 'Año',
    'garaje.detalle.vin' => 'VIN',
    'garaje.detalle.carroceria' => 'Carrocería',
    'garaje.detalle.tipo_combustible' => 'Tipo de combustible',
    'garaje.detalle.tipo_cambio' => 'Tipo de cambio',
    'garaje.detalle.potencia' => 'Potencia',
    'garaje.detalle.cilindrada' => 'Cilindrada',
    'garaje.detalle.fecha_alta' => 'Fecha de alta',

    // garaje - historial
    'garaje.historial.titulo' => 'Historial de mantenimiento',
    'garaje.historial.anadir' => 'Añadir mantenimiento',
    'garaje.historial.exportar_csv' => 'Exportar CSV',
    'garaje.historial.tipo' => 'Tipo',
    'garaje.historial.todos' => 'Todos',
    'garaje.historial.fecha_desde' => 'Fecha desde',
    'garaje.historial.fecha_hasta' => 'Fecha hasta',
    'garaje.historial.km_minimos' => 'Km mínimos',
    'garaje.historial.km_maximos' => 'Km máximos',
    'garaje.historial.coste_minimo' => 'Coste mínimo',
    'garaje.historial.coste_maximo' => 'Coste máximo',
    'garaje.historial.ordenar_por' => 'Ordenar por',
    'garaje.historial.fecha' => 'Fecha',
    'garaje.historial.kilometros' => 'Kilómetros',
    'garaje.historial.coste' => 'Coste',
    'garaje.historial.direccion' => 'Dirección',
    'garaje.historial.descendente' => 'Descendente',
    'garaje.historial.ascendente' => 'Ascendente',
    'garaje.historial.filtrar' => 'Filtrar',
    'garaje.historial.limpiar' => 'Limpiar',
    'garaje.historial.error_ajax' => 'No se pudo actualizar el historial',
    'garaje.historial.total_visibles' => 'Total visibles',
    'garaje.historial.coste_total_visible' => 'Coste total visible',
    'garaje.historial.primer_resultado' => 'Primer resultado',
    'garaje.historial.sin_resultados' => 'Sin resultados',
    'garaje.historial.anterior' => 'Anterior',
    'garaje.historial.siguiente' => 'Siguiente',
    'garaje.historial.sin_mantenimientos' => 'No hay mantenimientos que coincidan con los filtros aplicados',
    'garaje.historial.descripcion' => 'Descripción',
    'garaje.historial.acciones' => 'Acciones',
    'garaje.historial.no_indicada' => 'No indicada',
    'garaje.historial.no_indicados' => 'No indicados',
    'garaje.historial.editar' => 'Editar',
    'garaje.historial.eliminar' => 'Eliminar',
    'garaje.historial.confirmar_eliminar' => '¿Seguro que quieres eliminar este mantenimiento?',

    // garaje - formulario mantenimiento
    'garaje.mantenimiento.nuevo.titulo_pagina' => 'Añadir mantenimiento',
    'garaje.mantenimiento.nuevo.titulo' => 'Añadir mantenimiento',
    'garaje.mantenimiento.editar.titulo_pagina' => 'Editar mantenimiento',
    'garaje.mantenimiento.editar.titulo' => 'Editar mantenimiento',

    'garaje.mantenimiento.vehiculo' => 'Vehículo',
    'garaje.mantenimiento.fecha' => 'Fecha',
    'garaje.mantenimiento.tipo' => 'Tipo',
    'garaje.mantenimiento.descripcion' => 'Descripción',
    'garaje.mantenimiento.kilometros' => 'Kilómetros',
    'garaje.mantenimiento.coste' => 'Coste',
    'garaje.mantenimiento.volver' => 'Volver',
    'garaje.mantenimiento.guardar' => 'Guardar mantenimiento',
    'garaje.mantenimiento.guardar_cambios' => 'Guardar cambios',

    // garaje - mensajes mantenimiento
    'garaje.mantenimiento.error.vehiculo_no_valido' => 'Vehículo no válido',
    'garaje.mantenimiento.error.vehiculo_no_encontrado' => 'Vehículo no encontrado o sin permisos',
    'garaje.mantenimiento.error.fecha_tipo_obligatorios' => 'La fecha y el tipo son obligatorios',
    'garaje.mantenimiento.error.fecha_no_valida' => 'La fecha no es válida',
    'garaje.mantenimiento.error.tipo_maximo' => 'El tipo no puede superar los 100 caracteres',
    'garaje.mantenimiento.error.kilometros_entero' => 'Los kilómetros deben ser un número entero positivo',
    'garaje.mantenimiento.error.coste_valido' => 'El coste debe ser un número válido mayor o igual que cero',
    'garaje.mantenimiento.error.guardar' => 'No se pudo guardar el mantenimiento',
    'garaje.mantenimiento.ok.guardar' => 'Mantenimiento añadido correctamente',

    'garaje.mantenimiento.error.mantenimiento_no_valido' => 'Mantenimiento no válido',
    'garaje.mantenimiento.error.mantenimiento_no_encontrado' => 'Mantenimiento no encontrado o sin permisos',
    'garaje.mantenimiento.error.actualizar' => 'No se pudo actualizar el mantenimiento',
    'garaje.mantenimiento.ok.actualizar' => 'Mantenimiento actualizado correctamente',
    'garaje.mantenimiento.error.eliminar' => 'No se pudo eliminar el mantenimiento',
    'garaje.mantenimiento.ok.eliminar' => 'Mantenimiento eliminado correctamente',

    // comunidad - listado
    'comunidad.index.titulo_pagina' => 'Comunidad',
    'comunidad.index.titulo' => 'Comunidad',
    'comunidad.index.crear_publicacion' => 'Crear publicación',
    'comunidad.index.buscar_publicaciones' => 'Buscar publicaciones',
    'comunidad.index.placeholder_busqueda' => 'Contenido o autor',
    'comunidad.index.ordenar_por' => 'Ordenar por',
    'comunidad.index.orden.recientes' => 'Más recientes',
    'comunidad.index.orden.antiguas' => 'Más antiguas',
    'comunidad.index.orden.likes' => 'Más likes',
    'comunidad.index.orden.comentarios' => 'Más comentarios',
    'comunidad.index.aplicar_filtros' => 'Aplicar filtros',
    'comunidad.index.limpiar' => 'Limpiar',
    'comunidad.index.sin_publicaciones' => 'No se han encontrado publicaciones',
    'comunidad.index.por' => 'por',
    'comunidad.index.alt_imagen_publicacion' => 'Imagen de la publicación',
    'comunidad.index.comentario_singular' => 'comentario',
    'comunidad.index.comentario_plural' => 'comentarios',
    'comunidad.index.like_singular' => 'like',
    'comunidad.index.like_plural' => 'likes',
    'comunidad.index.dar_like' => 'Dar like',
    'comunidad.index.quitar_like' => 'Quitar like',
    'comunidad.index.ver_publicacion' => 'Ver publicación',
    'comunidad.index.editar_publicacion' => 'Editar publicación',
    'comunidad.index.eliminar_publicacion' => 'Eliminar publicación',
    'comunidad.index.confirmar_eliminar_publicacion' => '¿Seguro que quieres eliminar esta publicación?',
    'comunidad.index.publicacion_encontrada' => 'publicación encontrada',
    'comunidad.index.publicaciones_encontradas' => 'publicaciones encontradas',
    'comunidad.index.paginacion_aria' => 'Paginación de publicaciones',
    'comunidad.index.pagina_de' => 'Página {actual} de {total}',
    'comunidad.index.anterior' => 'Anterior',
    'comunidad.index.siguiente' => 'Siguiente',

    // comunidad - detalle
    'comunidad.detalle.titulo_pagina' => 'Detalle de publicación',
    'comunidad.detalle.titulo' => 'Detalle de publicación',
    'comunidad.detalle.error.cargar' => 'No se ha podido cargar la publicación',
    'comunidad.detalle.anadir_comentario' => 'Añadir comentario',
    'comunidad.detalle.comentario' => 'Comentario',
    'comunidad.detalle.publicar_comentario' => 'Publicar comentario',
    'comunidad.detalle.comentarios' => 'Comentarios',
    'comunidad.detalle.sin_comentarios' => 'Aún no hay comentarios en esta publicación',
    'comunidad.detalle.editar_comentario' => 'Editar comentario',
    'comunidad.detalle.eliminar_comentario' => 'Eliminar comentario',
    'comunidad.detalle.confirmar_eliminar_comentario' => '¿Seguro que quieres eliminar este comentario?',
    'comunidad.detalle.responder' => 'Responder',
    'comunidad.detalle.tu_respuesta' => 'Tu respuesta',
    'comunidad.detalle.publicar_respuesta' => 'Publicar respuesta',
    'comunidad.detalle.ver_una_respuesta' => 'Ver 1 respuesta',
    'comunidad.detalle.ver_respuestas' => 'Ver {total} respuestas',
    'comunidad.detalle.ocultar_respuestas' => 'Ocultar respuestas',
    'comunidad.detalle.cargando_respuestas' => 'Cargando respuestas...',
    'comunidad.detalle.error_cargar_respuestas' => 'No se pudieron cargar las respuestas',
    'comunidad.detalle.sin_respuestas' => 'No hay respuestas',
    'comunidad.detalle.volver' => 'Volver a comunidad',

    // comunidad - formularios
    'comunidad.form.nueva.titulo_pagina' => 'Crear publicación',
    'comunidad.form.nueva.titulo' => 'Crear publicación',
    'comunidad.form.contenido' => 'Contenido',
    'comunidad.form.imagen_opcional' => 'Imagen opcional',
    'comunidad.form.publicar' => 'Publicar',
    'comunidad.form.volver_comunidad' => 'Volver a comunidad',

    'comunidad.form.editar.titulo_pagina' => 'Editar publicación',
    'comunidad.form.editar.titulo' => 'Editar publicación',
    'comunidad.form.editar.error_cargar' => 'No se ha podido cargar la publicación',
    'comunidad.form.imagen_actual' => 'Imagen actual',
    'comunidad.form.alt_imagen_actual' => 'Imagen actual de la publicación',
    'comunidad.form.nueva_imagen_opcional' => 'Nueva imagen opcional',
    'comunidad.form.guardar_cambios' => 'Guardar cambios',
    'comunidad.form.volver_publicacion' => 'Volver a la publicación',

    'comunidad.form.editar_comentario.titulo_pagina' => 'Editar comentario',
    'comunidad.form.editar_comentario.titulo' => 'Editar comentario',
    'comunidad.form.editar_comentario.error_cargar' => 'No se ha podido cargar el comentario',
    'comunidad.form.editar_comentario.comentario' => 'Comentario',

    // comunidad - mensajes backend/ajax
    'comunidad.error.contenido_obligatorio' => 'El contenido es obligatorio',
    'comunidad.error.imagen_formato' => 'Formato de imagen no permitido',
    'comunidad.error.guardar_publicacion' => 'No se pudo guardar la publicación',
    'comunidad.ok.publicacion_creada' => 'Publicación creada correctamente',
    'comunidad.error.publicacion_no_valida' => 'Publicación no válida',
    'comunidad.error.publicacion_no_existe' => 'La publicación no existe',
    'comunidad.error.datos_respuesta_no_validos' => 'Datos de respuesta no válidos',
    'comunidad.error.comentario_responder_no_valido' => 'El comentario al que intentas responder no es válido',
    'comunidad.error.respuesta_vacia' => 'La respuesta no puede estar vacía',
    'comunidad.error.guardar_respuesta' => 'No se pudo guardar la respuesta',
    'comunidad.ok.respuesta_publicada' => 'Respuesta publicada correctamente',
    'comunidad.error.comentario_vacio' => 'El comentario no puede estar vacío',
    'comunidad.error.guardar_comentario' => 'No se pudo guardar el comentario',
    'comunidad.ok.comentario_publicado' => 'Comentario publicado correctamente',
    'comunidad.error.like_actualizar' => 'No se pudo actualizar el like',
    'comunidad.error.sin_permiso_editar_publicacion' => 'No tienes permiso para editar esta publicación',
    'comunidad.error.sin_permiso_eliminar_publicacion' => 'No tienes permiso para eliminar esta publicación',
    'comunidad.error.eliminar_publicacion' => 'No se pudo eliminar la publicación',
    'comunidad.ok.publicacion_eliminada' => 'Publicación eliminada correctamente',
    'comunidad.error.datos_no_validos' => 'Datos no válidos',
    'comunidad.error.comentario_no_valido' => 'El comentario no es válido',

    'comunidad.error.subir_imagen' => 'No se pudo subir la imagen',
    'comunidad.error.actualizar_publicacion' => 'No se pudo actualizar la publicación',
    'comunidad.ok.publicacion_actualizada' => 'Publicación actualizada correctamente',

    'comunidad.error.comentario_no_existe' => 'El comentario no existe',
    'comunidad.error.sin_permiso_editar_comentario' => 'No tienes permiso para editar este comentario',
    'comunidad.error.comentario_contenido_obligatorio' => 'El contenido del comentario es obligatorio',
    'comunidad.error.actualizar_comentario' => 'No se pudo actualizar el comentario',
    'comunidad.ok.comentario_actualizado' => 'Comentario actualizado correctamente',
    'comunidad.error.sin_permiso_eliminar_comentario' => 'No tienes permiso para eliminar este comentario',
    'comunidad.error.eliminar_comentario' => 'No se pudo eliminar el comentario',
    'comunidad.ok.comentario_eliminado' => 'Comentario eliminado correctamente',

    // perfil
    'perfil.error.cargar' => 'No se ha podido cargar el perfil',
    'perfil.error.no_valido' => 'Perfil no válido',
    'perfil.error.no_existe' => 'El perfil no existe',
    'perfil.error.usuario_no_encontrado' => 'Usuario no encontrado',
    'perfil.error.imagen_obligatoria' => 'Debes seleccionar una imagen',
    'perfil.error.subir_foto' => 'No se pudo subir la foto de perfil',
    'perfil.error.archivo_no_valido' => 'El archivo subido no es válido',
    'perfil.error.imagen_tamanyo' => 'La imagen no puede superar los 3 MB',
    'perfil.error.imagen_formato' => 'Solo se permiten imágenes JPG, PNG o WEBP',
    'perfil.error.crear_directorio' => 'No se pudo crear el directorio de fotos de perfil',
    'perfil.error.guardar_foto' => 'No se pudo guardar la foto de perfil',
    'perfil.ok.foto_actualizada' => 'Foto de perfil actualizada',
    'perfil.error.campos_obligatorios' => 'Todos los campos son obligatorios',
    'perfil.error.nombre_reglas' => 'El nombre de usuario no cumple las reglas permitidas',
    'perfil.error.email_no_valido' => 'El correo electrónico no es válido',
    'perfil.error.nombre_en_uso' => 'El nombre de usuario ya está en uso',
    'perfil.error.email_en_uso' => 'El correo electrónico ya está en uso',
    'perfil.ok.actualizado' => 'Perfil actualizado correctamente',
    'perfil.error.password_obligatoria' => 'Todos los campos de contraseña son obligatorios',
    'perfil.error.password_actual' => 'La contraseña actual no es correcta',
    'perfil.error.password_no_coincide' => 'Las nuevas contraseñas no coinciden',
    'perfil.error.password_requisitos' => 'La nueva contraseña debe tener mínimo 8 caracteres, una mayúscula, una minúscula y un número',
    'perfil.error.password_igual' => 'La nueva contraseña no puede ser igual a la actual',
    'perfil.ok.password_actualizada' => 'Contraseña actualizada correctamente',

    'perfil.ver.titulo_pagina' => 'Perfil',
    'perfil.ver.titulo_de' => 'Perfil de',
    'perfil.ver.alt_foto' => 'Foto de perfil de',
    'perfil.ver.sin_foto' => 'Sin foto',
    'perfil.ver.cambiar_foto' => 'Cambiar foto de perfil',
    'perfil.ver.nueva_foto' => 'Nueva foto',
    'perfil.ver.actualizar_foto' => 'Actualizar foto',
    'perfil.ver.editar_datos' => 'Editar datos del perfil',
    'perfil.ver.nombre_usuario' => 'Nombre de usuario',
    'perfil.ver.email' => 'Correo electrónico',
    'perfil.ver.guardar_cambios' => 'Guardar cambios',
    'perfil.ver.cambiar_password' => 'Cambiar contraseña',
    'perfil.ver.password_actual' => 'Contraseña actual',
    'perfil.ver.password_nueva' => 'Nueva contraseña',
    'perfil.ver.password_nueva_repetida' => 'Repetir nueva contraseña',
    'perfil.ver.garaje_publico' => 'Garaje público',
    'perfil.ver.sin_vehiculos' => 'Este usuario todavía no tiene vehículos en su garaje',
    'perfil.ver.sin_imagen' => 'Sin imagen',
    'perfil.ver.alt_vehiculo' => 'Imagen de',
    'perfil.ver.ver_detalles' => 'Ver detalles',
    'perfil.ver.publicaciones' => 'Publicaciones',
    'perfil.ver.sin_publicaciones' => 'Este usuario todavía no tiene publicaciones',
    'perfil.ver.alt_publicacion' => 'Imagen de la publicación',
    'perfil.ver.comentario_singular' => 'comentario',
    'perfil.ver.comentario_plural' => 'comentarios',
    'perfil.ver.like_singular' => 'like',
    'perfil.ver.like_plural' => 'likes',
    'perfil.ver.ver_publicacion' => 'Ver publicación',

    // perfil - vehículo público
    'perfil.vehiculo.error.cargar' => 'No se ha podido cargar el vehículo',
    'perfil.vehiculo.error.no_valido' => 'Vehículo no válido',
    'perfil.vehiculo.error.no_existe' => 'El vehículo no existe',
    'perfil.vehiculo.titulo_pagina' => 'Vehículo público',
    'perfil.vehiculo.propietario' => 'Propietario',
    'perfil.vehiculo.alt_imagen' => 'Imagen del vehículo',
    'perfil.vehiculo.detalles_publicos' => 'Detalles públicos',
    'perfil.vehiculo.any' => 'Año',
    'perfil.vehiculo.carroceria' => 'Carrocería',
    'perfil.vehiculo.combustible' => 'Combustible',
    'perfil.vehiculo.cambio' => 'Cambio',
    'perfil.vehiculo.potencia' => 'Potencia',
    'perfil.vehiculo.cilindrada' => 'Cilindrada',
    'perfil.vehiculo.volver_perfil' => 'Volver al perfil',

    // diagnóstico ia
    'diagnostico.titulo_pagina' => 'Diagnóstico asistido',
    'diagnostico.titulo' => 'Diagnóstico asistido',
    'diagnostico.descripcion' => 'Describe los síntomas del vehículo y TorqHub analizará posibles causas mediante un sistema experto basado en reglas.',
    'diagnostico.reiniciar' => 'Reiniciar chat',
    'diagnostico.ia_nombre' => 'TorqHub IA',
    'diagnostico.usuario' => 'Tú',
    'diagnostico.mensaje_inicial' => 'Hola, dime qué le ocurre a tu coche. Por ejemplo: “el coche no arranca y hace click”.',
    'diagnostico.resultados_intro' => 'He encontrado estas posibles causas:',
    'diagnostico.confianza_aproximada' => 'Confianza aproximada',
    'diagnostico.coincidencias_detectadas' => 'Coincidencias detectadas',
    'diagnostico.recomendacion' => 'Recomendación',
    'diagnostico.sin_resultados' => 'No he encontrado una causa clara. Prueba describiendo síntomas más concretos como ruido, temperatura, arranque, frenos, dirección o pérdida de potencia.',
    'diagnostico.label_sintomas' => 'Síntomas del vehículo',
    'diagnostico.placeholder_sintomas' => 'Escribe aquí los síntomas...',
    'diagnostico.boton_analizar' => 'Analizar',
    'diagnostico.estado_analizando' => 'Analizando...',
    'diagnostico.error.sintomas_obligatorios' => 'Debes escribir los síntomas del vehículo',
    'diagnostico.error.analisis' => 'Ha ocurrido un error al analizar los síntomas',
    'diagnostico.error.conexion' => 'No se ha podido conectar con el sistema de diagnóstico',

    // diagnóstico ia - causas
    'diagnostico.causa.bateria.titulo' => 'Batería descargada o en mal estado',
    'diagnostico.causa.bateria.recomendacion' => 'Revisar la carga de la batería, bornes y alternador antes de sustituirla.',
    'diagnostico.causa.arranque.titulo' => 'Fallo en el motor de arranque',
    'diagnostico.causa.arranque.recomendacion' => 'Comprobar motor de arranque, relé y conexiones eléctricas.',
    'diagnostico.causa.encendido.titulo' => 'Problema de bujías o encendido',
    'diagnostico.causa.encendido.recomendacion' => 'Revisar bujías, bobinas y sistema de encendido.',
    'diagnostico.causa.filtros.titulo' => 'Filtro de aire o combustible obstruido',
    'diagnostico.causa.filtros.recomendacion' => 'Revisar filtros y sustituirlos si están sucios.',
    'diagnostico.causa.sobrecalentamiento.titulo' => 'Sobrecalentamiento del motor',
    'diagnostico.causa.sobrecalentamiento.recomendacion' => 'Parar el vehículo y revisar refrigerante, radiador, termostato y ventilador.',
    'diagnostico.causa.frenos.titulo' => 'Fallo en frenos',
    'diagnostico.causa.frenos.recomendacion' => 'Revisar pastillas, discos, líquido de frenos y posibles fugas.',
    'diagnostico.causa.embrague.titulo' => 'Problema de embrague',
    'diagnostico.causa.embrague.recomendacion' => 'Revisar desgaste del embrague y sistema hidráulico.',
    'diagnostico.causa.neumaticos.titulo' => 'Neumáticos o alineación incorrecta',
    'diagnostico.causa.neumaticos.recomendacion' => 'Comprobar presión, equilibrado, alineación y estado de los neumáticos.',

    // garaje - eliminar vehículo
    'garaje.eliminar.titulo_pagina' => 'Eliminar vehículo',
    'garaje.eliminar.titulo' => 'Eliminar vehículo',
    'garaje.eliminar.error.cargar' => 'No se ha podido cargar el vehículo para eliminar',
    'garaje.eliminar.confirmacion' => '¿Seguro que quieres eliminar este vehículo?',
    'garaje.eliminar.cancelar' => 'Cancelar',
    'garaje.eliminar.eliminar' => 'Eliminar',

    // admin
    'admin.titulo_pagina' => 'Panel de administración',
    'admin.titulo' => 'Panel de administración',
    'admin.descripcion' => 'Solo accesible para administradores',

        // garaje - mensajes de vehículo
    'garaje.vehiculo.error.carroceria_no_valida' => 'La carrocería no es válida',
    'garaje.vehiculo.error.combustible_no_valido' => 'El tipo de combustible no es válido',
    'garaje.vehiculo.error.cambio_no_valido' => 'El tipo de cambio no es válido',
    'garaje.vehiculo.error.potencia_entero' => 'La potencia en CV debe ser un número entero positivo',
    'garaje.vehiculo.error.cilindrada_entero' => 'La cilindrada debe ser un número entero positivo',
    'garaje.vehiculo.error.marca_modelo_any_obligatorios' => 'Marca, modelo y año son obligatorios',
    'garaje.vehiculo.error.marca_modelo_obligatorios' => 'Marca y modelo son obligatorios',
    'garaje.vehiculo.error.no_valido' => 'Vehículo no válido',
    'garaje.vehiculo.error.no_encontrado' => 'Vehículo no encontrado',
    'garaje.vehiculo.error.no_encontrado_permisos' => 'Vehículo no encontrado o sin permisos',
    'garaje.vehiculo.error.guardar' => 'No se pudo guardar el vehículo',
    'garaje.vehiculo.error.actualizar' => 'No se pudo actualizar el vehículo',
    'garaje.vehiculo.error.eliminar' => 'No se pudo eliminar el vehículo',
    'garaje.vehiculo.ok.creado' => 'Vehículo añadido correctamente',
    'garaje.vehiculo.ok.actualizado' => 'Vehículo actualizado correctamente',
    'garaje.vehiculo.ok.eliminado' => 'Vehículo eliminado correctamente',

    // garaje - imagen de vehículo
    'garaje.vehiculo.imagen.error.subir' => 'No se pudo subir la imagen del vehículo',
    'garaje.vehiculo.imagen.error.archivo_no_valido' => 'El archivo subido no es válido',
    'garaje.vehiculo.imagen.error.tamanyo' => 'La imagen no puede superar los 3 MB',
    'garaje.vehiculo.imagen.error.formato' => 'Solo se permiten imágenes JPG, PNG o WEBP',
    'garaje.vehiculo.imagen.error.crear_directorio' => 'No se pudo crear el directorio de imágenes de vehículos',
    'garaje.vehiculo.imagen.error.guardar' => 'No se pudo guardar la imagen del vehículo',

    // garaje - vin backend
    'garaje.vin.error.obligatorio' => 'Debes introducir un VIN',
    'garaje.vin.ok.cache' => 'VIN encontrado en caché',
    'garaje.vin.ok.api' => 'VIN consultado en la API externa',
    'garaje.vin.error.cache' => 'No se pudo guardar la caché del VIN',

    // garaje - filtros backend
    'garaje.filtros.error.fecha_desde_no_valida' => 'La fecha desde no es válida',
    'garaje.filtros.error.fecha_hasta_no_valida' => 'La fecha hasta no es válida',
    'garaje.filtros.error.fecha_desde_mayor' => 'La fecha desde no puede ser mayor que la fecha hasta',
    'garaje.filtros.error.km_minimos' => 'Los kilómetros mínimos deben ser un número entero positivo',
    'garaje.filtros.error.km_maximos' => 'Los kilómetros máximos deben ser un número entero positivo',
    'garaje.filtros.error.km_minimos_mayores' => 'Los kilómetros mínimos no pueden ser mayores que los máximos',
    'garaje.filtros.error.coste_minimo' => 'El coste mínimo no es válido',
    'garaje.filtros.error.coste_maximo' => 'El coste máximo no es válido',
    'garaje.filtros.error.coste_minimo_mayor' => 'El coste mínimo no puede ser mayor que el coste máximo',
    'garaje.filtros.error.orden_campo' => 'El campo de ordenación no es válido',
    'garaje.filtros.error.orden_direccion' => 'La dirección de ordenación no es válida',

    // garaje - opciones de selects
    'garaje.opcion.carroceria.coche_pequeno' => 'Coche pequeño',
    'garaje.opcion.carroceria.sedan' => 'Sedán',
    'garaje.opcion.carroceria.familiar' => 'Familiar',
    'garaje.opcion.carroceria.cabrio' => 'Cabrio',
    'garaje.opcion.carroceria.coupe' => 'Coupé',
    'garaje.opcion.carroceria.suv_4x4' => 'SUV/4x4',
    'garaje.opcion.carroceria.monovolumen' => 'Monovolumen',
    'garaje.opcion.carroceria.furgoneta' => 'Furgoneta',
    'garaje.opcion.carroceria.otros' => 'Otros',

    'garaje.opcion.combustible.gasolina' => 'Gasolina',
    'garaje.opcion.combustible.diesel' => 'Diésel',
    'garaje.opcion.combustible.electrico' => 'Eléctrico',
    'garaje.opcion.combustible.electro_gasolina' => 'Eléctrico/gasolina',
    'garaje.opcion.combustible.electro_diesel' => 'Eléctrico/diésel',
    'garaje.opcion.combustible.gas_natural' => 'Gas natural (CNG)',
    'garaje.opcion.combustible.etanol' => 'Etanol',
    'garaje.opcion.combustible.hidrogeno' => 'Hidrógeno',
    'garaje.opcion.combustible.glp' => 'Gas licuado (GLP)',
    'garaje.opcion.combustible.otros' => 'Otros',

    'garaje.opcion.cambio.automatico' => 'Automático',
    'garaje.opcion.cambio.manual' => 'Manual',

    // middlewares
    'middleware.auth.error.login_requerido' => 'Debes iniciar sesión para acceder a esta página',
    'middleware.admin.error.login_requerido' => 'Debes iniciar sesión',
    'middleware.admin.error.acceso_denegado' => '403 - Acceso denegado',

    // servicio vin
    'garaje.vin.error.formato' => 'El VIN debe tener 17 caracteres y no puede contener I, O ni Q',
    'garaje.vin.error.curl_no_disponible' => 'cURL no está disponible en PHP',
    'garaje.vin.error.consulta_api' => 'No se pudo consultar la API VIN',
    'garaje.vin.error.codigo_http' => 'La API VIN respondió con código HTTP {codigo}',
    'garaje.vin.error.json_no_valido' => 'La respuesta de la API VIN no es un JSON válido',
    'garaje.vin.error.sin_resultados' => 'La API VIN no devolvió resultados válidos',
];
